- lib/sys/target.flow
Task https://trello.com/c/OJXNngb7/4716-video-player-glitches-on-mac
> Testing Chrome in Mac

- platforms/js/Native.hx
> Altered 'replace' native function to return proper values

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
https://github.com/area9innovation/flow9/pull/198
> Introduce new paragraph style that allows to render paragraph in single line

- lib/form/paragraph3.flow
https://github.com/area9innovation/innovation/pull/554
> build highlighting for ghost elements, minor refactoring

- lib/fform/fform.flow
- lib/material/material_ui.flow
Added opportunity to select a player in MMultiAudioPlayer element.
> Multiplayer: added opportunity to switch between players

- platforms/common/cpp/core/JitProgram.cpp
- platforms/common/cpp/core/JitProgram.h
- platforms/qt/main.cpp
- platforms/qt/qt-backend/RunParallel.cpp
> Jit overlap solution

- lib/formats/mime/mime_types.flow
Task https://trello.com/c/qF2sCL34/4980-video-doesnt-play-in-safari
> MIME type for webm

- lib/pebbles/pebble_hierarchy.flow
https://trello.com/c/XOSbbnqj/2918-new-pebble-design
https://git.area9lyceum.com/Lyceum/lyceum/compare/master...curator_hierarchy
> pebble : hierarchy

- lib/material/internal/material_menu.flow
- lib/material/material.flow
A style to be able to control tooltip in multiselect dropdown.
> added MShowTooltip style to multi-select dropdown

- lib/ui/imagedecorated.flow
Task https://trello.com/c/agd8OXbh/4572-coach-should-start-talking-when-the-screen-is-fully-loaded
> onLoaded for images

- lib/text/translationsimplestrings.flow
- lib/text/xliffprettyprint.flow
Task https://trello.com/c/4ZSpEWr0/5529-translation-files-encode-the-xliff-tag
> Translation: Remove escaping for g and x tag

- lib/pebbles/pebble_hierarchy.flow
Fixed setViewForPebbledHierarchyFilterParameters for search by children of PebbledHierarchyItem.
related to https://git.area9lyceum.com/Lyceum/lyceum/commit/fd3dfe7052cdf0541c5c46cd1a3a1c9ec9c397f8
> Fixed setViewForPebbledHierarchyFilterParameters

- lib/ui/imagedecorated.flow
- lib/ui/imagedecorated_editor_types.flow
- lib/ui/imagedecorated_editor_utils.flow
- lib/ui/imagedecoratedstructs.flow
https://trello.com/c/rC3iQPYQ/3856-add-dimmer-feature-in-simple-picture-editor
> Add Dimmer feature in simple picture editor

- lib/form/paragraph.flow
- lib/text/localization.flow
in scope of https://trello.com/c/6B3yEwAM/570-service-to-insert-soft-hyphenation-in-a-text
> Made hyphenation point work in JS by showing small dot

- lib/form/form.flow
- lib/form/renderform.flow
- lib/rendersupport.flow
- platforms/common/cpp/gl-gui/GLRenderSupport.cpp
- platforms/common/cpp/gl-gui/GLTextClip.cpp
- platforms/common/cpp/gl-gui/GLTextClip.h
- platforms/csharp/FlowRuntime/RenderSupport.cs
- platforms/csharp/WindowsRT/RenderSupportXAML.cs
- platforms/java/com/area9innovation/flow/RenderSupport.java
- platforms/java/javafx/com/area9innovation/flow/javafx/FxRenderSupport.java
- platforms/js/RenderSupport.hx
- platforms/js/RenderSupportJS.hx
- platforms/js/RenderSupportJSPixi.hx
- platforms/js/RenderSupportNodeJs.hx
- platforms/js/TextClip.hx
Try to tune wigi editor in JS mode
deferred option is disabled under NEW flag only. other settings are permanent
1) Hidden Text input in wigi editor should not induce animate
2) Animate should not induce recursive stage's invalidation
3) Do not use deferred in text input pipeline - it lead to several animate calls
4) Do not call html2text for the text in the editor
> Wigi editor performance tuning in JS

- lib/form/paragraph.flow
- lib/text/localization.flow
https://trello.com/c/9lkrdGZO/622-some-japanese-characters-missing-in-paragraphs
> Fixed loss of Japanese charactes in the end of lines which was introduced by hyphenation fixes

- lib/pebbles/pebble_controller.flow
https://trello.com/c/h5rrDNsI/964-restore-the-last-pebble
> Open last pebble in js;

- lib/ui/combobox.flow
@anatolmykolenko hi Anatol, please check if it's safe to change combobox behaviour here. The problem is the same as the one we had with tropic - it didn't work correctly for long dropdowns where we have a scrollbar, so I have added measuring of delta on mouseDown and mouseUp
> Fix for scrolling in long drop down lists in combobox for Form

- lib/ui/imagedecorated.flow
Refactored decorations. Make Custom shadow for js target until it will be fixed by core team
> Add shadow temporary customization for js target

- lib/text/translation.flow
Task https://trello.com/c/AGr0rrUX/6455-improve-algorithm-for-replacement-in-phrasetranslation
> Run doReplacement only if translated string is equal to source

- lib/formats/json/json.flow
- platforms/common/haxe/HaxeRuntime.hx
- platforms/js/Native.hx
This is 2 times faster with json/test/speed_test.flow
@alstrup , @ykuzmenko73 , please take a look
> JS Native json

- lib/material/internal/material_player.flow
Task https://trello.com/c/qKLOGC4u/6601-qa-educator-and-learner-side-activity-probe-video-component-problem
> Black background for Mediaplayer

- lib/pebbles/pebble_parameters.flow
- Fix https://trello.com/c/PnYY5BT0/6743-remove-t-parameter-from-url-when-leaving-the-workflow-page;
@aatkachenko FYI
> CheckPebble;

- lib/text/languages.flow
added languages with country codes
related trello card:
https://trello.com/c/n0MrLfCl/6932-add-support-for-ietf-language-tag-subset
> added new languages

- lib/text/languages.flow
Task https://trello.com/c/Rolub9O3/7335-translation-it-is-impossible-to-select-language-for-translation
> Disable languages without language code

- lib/text/languages.flow
> Filter extra languages

- lib/material/internal/material_button.flow
- lib/material/material.flow
Style allows to change direction of opening dial menu.
Useful if your FloatingButton is on the top of the application:
> added new style for floating button

- lib/ds/hashmap.flow
> attempt to fix HashMap

- lib/form/paragraph.flow
https://github.com/area9innovation/innovation/pull/1252
> Add argument that allows to disable word wrapping after hyphen

- tools/flowc/backends/javascript/fi2javascript_compile.flow
- tools/flowc/flowc_version.flow
@alstrup , @dmitry-vlasov , don't you mind this minor fix to show actual links for messages sources in JS console?
> inline console.log for correct links

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
- lib/tropic/tropic_paragraph.flow
paired with https://github.com/area9innovation/innovation/pull/1314
in branch:
in master:
> wigify: fix issue with GeneralIndent

- lib/form/formmetrics.flow
- lib/form/paragraph3.flow
- platforms/js/PixiWorkarounds.hx
This PR fixes lost of precision in IE for measuring the text.
> fix wrong metrics in IE

- doc/lingo.markdown
lib/lingo/flow.lingo to tools/flowc/flow.lingo
> Changes in paths

- lib/form/paragraph3.flow
- lib/tropic/tropic_paragraph.flow
https://github.com/area9innovation/innovation/pull/1351
> Get rid of tight width calculating

- lib/material/internal/filebrowser/material_filebrowser_internal.flow
https://trello.com/c/2FmXHomR/6774
> FB: compact List view

- lib/text/translationutils.flow
https://trello.com/c/Rl1IBYyY/588-sso-content-package-language-and-sso
> Fixed getLanguageName in translationutils

- lib/promise.flow
- tests/test_promises.flow
Warning instead of assert, refactoring and small optimizations
- don't fire until all promises are done (either fulfilled or rejected)
- minor refactoring
> Fix promises

- lib/text/translationutils.flow
Task https://trello.com/c/DDABqjbI/8693-remove-error-msg-if-no-json-file-created-for-ui-translations
> Change loading path for json files

- lib/runtime.flow
https://trello.com/c/NiSWoAmU/695-hide-resize-to-fit-option
https://git.area9lyceum.com/Lyceum/lyceum/pulls/1360
https://github.com/area9innovation/innovation/pull/1429
https://github.com/area9innovation/cog9platform/pull/1380
> Wigi media block: hide resize to fit

- lib/tropic/tropic_paragraph.flow
- lib/tropic/tropic_paragraph_preparation.flow
I made a mistake implementing tropic paragraphs and misunderstood baseline meaning. Now I see, I believe :)
> Proper handle of baseline shift

- lib/text/translationutils.flow
Task https://trello.com/c/Lf2Hy8Yi/8970-xliff-extraction-regression
> Fixed reduced XLIFF extraction

- lib/material/material_dialog.flow
https://trello.com/c/VzqSmUan/1295-add-new-type-of-presentation-rich-static-text
not exactly relates to the task, but wished to be done right after
> added MDialogWithCallbacksIgnoreEnter to union

- lib/excel_datetime.flow
- lib/material/extra/calendar/calendar.flow
- lib/material/extra/material2html/engine.flow
There we have dependence of flow9 of innovation, what is wrong? These files should be probably moved somewhere in innovation repo.
> Moved all expression-related files into lib/wigi/expr

- lib/form/gui.flow
- lib/formats/html/html2form.flow
- lib/material/internal/material_tree.flow
- lib/ui/imagedecorated.flow
- lib/ui/imagedecoratedstructs.flow
https://trello.com/c/CfFtJ9P9/8739-prime-graphics-used-in-probes-cannot-turn-off-zoom-feature
> 8739 picture custom zoom

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
> Implement interline highlighting option

- tools/flowc/flowc_version.flow
- tools/flowc/manipulation/mangle.flow
- tools/flowc/manipulation/specialization_js.flow
Fixed issue with generic lambdas - all top level lambdas now converted into functions
> Flowc spec lambda fix

- doc/faq.markdown
https://trello.com/c/0ecEmvsE/9268-review-something-is-wrong-with-the-date-comparison
not a solution but explains the reasons
> FAQ. The timestamp difference explanation

- lib/form/paragraph.flow
- lib/text/localization.flow
paired with https://github.com/area9innovation/innovation/pull/1576
> Words to hyphenate - refactoring

- lib/text/unicodecharacters.flow
Task https://trello.com/c/DEPJsDY8/9957-some-text-in-prime-not-translatable
Related PR https://git.area9lyceum.com/Lyceum/lyceum/pulls/1830
> containsSymbolFromCategoryUnicode

- platforms/js/PixiWorkarounds.hx
- platforms/js/Platform.hx
https://trello.com/c/6eZFl3Ql/9042-learner-text-overlap-in-android
> 9042 samsung font scale

- lib/material/internal/material_scroll.flow
_trello_ : https://trello.com/c/6CzgQgOQ/1528-specifications-disappear-if-selections-are-created-randomly
> MRecyclerGrid: Fix update's issue after scrollToItem

- lib/loop.flow
res was changed only on last iteration
> fix small bug in foldUntil

- lib/material/internal/material_textinput_state.flow
- lib/material/material.flow
https://trello.com/c/O9pgHxw7/10326
> MTextInputScrollStyle

- lib/material/internal/material_button.flow
- lib/material/material.flow
- lib/material/tests/test_mchip.flow
Task https://trello.com/c/uFGDL1UK/10120-educator-content-create-content-in-content-tab
Use case https://git.area9lyceum.com/Lyceum/lyceum/pulls/2036/files
> Allow using MIcon and customizing CloseButton in MChip

- platforms/js/FontLoader.hx
- tests/mtext_test.flow
- www/js/webfont_debug.js
It reduces delay because of fonts from 3000-4000 ms down to 500-800
Paired: https://git.area9lyceum.com/Lyceum/lyceum/pulls/2117
> FontLoader: call StartFlowMain immediately after adding checked font into DOM

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
https://github.com/area9innovation/innovation/pull/1854
this is only hot fix.
We need to change wigify to fix that for general cases
> Support overlapping of words

- lib/material/internal/material_player.flow
https://trello.com/c/q1KInakn/10916-fix-descriptive-labels-for-ui-elements
> Button titles for MVideoPlayer controls

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
Reverts area9innovation/flow9#652
> Revert "Support overlapping of words"

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
Reverts area9innovation/flow9#655
> Revert "Revert "Support overlapping of words""

- lib/material/internal/material_tabs.flow
- lib/material/material.flow
> introduce MTabChangeIndicatorColor

- lib/text/languages.flow
Task https://trello.com/c/cKlDAw5L/11272-few-changes-in-the-list-of-languages
> New language names

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
https://github.com/area9innovation/innovation/compare/fit_long_words_feature?expand=1
> Introduce new fit long words feature for render paragraph

- lib/formats/json/json.flow
- lib/formats/json/json_compact.flow
> fjson2json: in-place compacting to save memory

- lib/material/internal/material_player.flow
- lib/material/internal/material_slider.flow
- lib/material/material.flow
https://trello.com/c/qCKQYTKR/11376-prod-progress-in-video-player-is-not-visible-until-focused
colors agreed by Mads
> Material Player. Primary color for timeline

- lib/material/internal/material_player.flow
- lib/material/material.flow
> MVideoPlayer fix selected color

- lib/material/internal/material_menu.flow
https://trello.com/c/uOynDLTT/11614-412b-custom-controls
> Accesibility - wrong role for DropDown component

- lib/material/internal/material_ellipsis.flow
https://trello.com/c/EBEQZ2gb/10614-export-of-the-big-charts-to-pdf-looks-not-readable
> ellipsis text serialize issue

- platforms/java/com/area9innovation/flow/HttpServerSupport.java
Based on stackoverflow it is the best way
https://stackoverflow.com/questions/309424/how-do-i-read-convert-an-inputstream-into-a-string-in-java
> HttpServerSupport.readInputStream tune performance and memory usage

- platforms/js/TextClip.hx
> TextClip: tune setTextAndStyle in JS

- platforms/java/com/area9innovation/flow/FlowJwt.java
Change the JWT implementation.
> Changed the Jwt implementation, so it is much simpler

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
- lib/material/internal/material_typography.flow
> Implement grouping words which have same heading level under appropriate tags

- lib/material/extra/icon_picker/material_icon_groups.flow
- lib/material/internal/material_icons.flow
- lib/pebbles/pebble_controller.flow
- lib/pebbles/pebble_hierarchy.flow
https://trello.com/c/ijkPk0dE/11676-we-need-pebble-feature-to-make-a-pebble-sticky
> Pinparameter

- lib/material/internal/material_tabs.flow
- lib/material/material.flow
> Add MTabsIconTitleAlign to MDynamicTabs

- lib/form/paragraph3.flow
Apply scaling and reflowing of paragraph after too long word getting of too long word in paragraph.
> Fit long words feature 2.0

- lib/math/math.flow
- lib/math/stringmath.flow
Does this belong here?
Or should it be a local function.
> Added an string to integer function that can fail

- lib/material/internal/material_pickers.flow
- lib/material/material.flow
MNoHeader removes infoSection of MDatePicker;
MMultiDate allows to choose multiple dates with second click after date selected;
> Material: Add MMultiDate and MNoHeader styles to MDatePicker

- lib/form/paragraph.flow
- lib/form/paragraph3.flow
https://github.com/area9innovation/innovation/pull/2093
> Wigi diff: improve strike for deleted paragraph

- lib/timer.flow
- platforms/java/com/area9innovation/flow/Native.java
Each thread should have own timer, otherwise we had only one timer thread;
> Improved timer for multi-thread java applications

- lib/material/extra/calendar/calendar.flow
https://trello.com/c/eYhKaHT1/12435-family-dashboard
> Calendar customization

- lib/text/languages.flow
- lib/ui/fontmapping.flow
Task https://trello.com/c/ZiDXZh1I/12912-learner-landing-page-is-displayed-in-english-when-langde-du
> Support de-DU in getLang()

- lib/form/paragraph.flow
https://github.com/area9innovation/innovation/pull/2154
> Wigi: tune IgnoreLetterspacingOnReflow

- lib/formats/html/html2form.flow
- lib/ui/imagedecorated.flow
- lib/ui/imagedecoratedstructs.flow
https://trello.com/c/RYYe1R9U/12636-introduce-a-new-zoomed-images-viewer
Other PRs in innovation and lyceum repos.
> Add new image zoomer

- lib/formats/html/html.flow
- platforms/java/com/area9innovation/flow/Native.java
It helps a lot if string is large and contains many "%xx"
> Added native urlDecode for java target

- lib/material/material_ui.flow
- lib/material/tests/test_card_flip.flow
https://git.area9lyceum.com/Lyceum/lyceum/pulls/2949
> [Flipping Card] Add FAnimationPercent

- lib/fs/filesystem.flow
- platforms/java/com/area9innovation/flow/FlowFileSystem.java
needed for: https://git.area9lyceum.com/Lyceum/lyceum/pulls/3009
https://trello.com/c/S73Zh2wW/901-isams-additional-attributes
> Download file and file utilites implementation for Java target

- platforms/java/com/area9innovation/flow/FlowFileSystem.java
- platforms/java/com/area9innovation/flow/HttpSupport.java
needed to upload reports here: https://trello.com/c/WSdhkEW7/975-isams-reports
> Java uploadNativeFile implementation

- lib/material/internal/material_datatable.flow
- lib/material/material.flow
- lib/material/material2tropic.flow
- lib/material/tests/test_mdatatable_light.flow
https://trello.com/c/qgm0xFoj/13238-super-admin-cant-load-user-list-on-us-server-out-of-memory
> Implemented MLightweightDataTable.

- lib/material/internal/filebrowser/material_filebrowser_internal.flow
Task : https://trello.com/c/V1WtqUJb/13319-spanish-ui-on-learner
Vladimir, please, check is it save to translate property name
> Translate FB properties

- platforms/js/MediaRecorderSupportNodeJs.hx
- platforms/js/MediaStreamSupportNodeJs.hx
- platforms/js/ProgressiveWebTools.hx
- platforms/js/RenderSupport3DNodeJs.hx
- tools/flowc/backends/javascript/fi2javascript_assemble.flow
Add missing stubs for rhapsode cmd line tools.
> Add missing stubs

- lib/material/internal/material_carousel.flow
- lib/material/material.flow
- lib/material/tests/test_mcarousel.flow
_trello_ : https://trello.com/c/U05WAVR7/1990-replace-title-and-subtitle-by-wigi-in-carousel
_innovation related PR_ : https://github.com/area9innovation/innovation/pull/2338
> Carousel : bug fixed and add MCarouselTextFontStyle style

- lib/material/extra/calendar/calendar.flow
https://trello.com/c/ffBhOo7X/1049-isams-attendance-reporting
> Calendar: hide weekends style

- lib/ui/imagedecorated.flow
https://trello.com/c/cPiK2IsK/14093-add-padding-to-the-text-box-in-slideshows
> Add borders in ImageTextBox

- tools/flowc/flowc_local.flow
- tools/flowc/flowc_usage.flow
- tools/flowc/flowc_version.flow
- tools/flowc/manipulation/xliff.flow
Task https://trello.com/c/Gu2JiYqr
Usage:
`flowc1 xliff=1 xliff-filter=curator/,educator/,workflow/  learner/learner.flow`
> xliff-filter parameter

- tools/flowc/flowc_local.flow
- tools/flowc/flowc_usage.flow
- tools/flowc/flowc_version.flow
- tools/flowc/manipulation/xliff.flow
This reverts commit 153ff73a7a07a1f723dd6bb746d71bbd2a7d47b0.
> Revert "xliff-filter parameter (#833)"

- tools/flowc/flowc_local.flow
- tools/flowc/flowc_usage.flow
- tools/flowc/flowc_version.flow
- tools/flowc/manipulation/xliff.flow
Task https://trello.com/c/Gu2JiYqr
Usage:
`flowc1 xliff=1 xliff-filter=curator/,educator/,workflow/ learner/learner.flow`
Discussions in previous PR https://github.com/area9innovation/flow9/pull/833
> Xliff filter parameter for flowc

- lib/ui/fontmapping.flow
Related PR https://git.area9lyceum.com/Lyceum/lyceum/pulls/3491
> Add fn to check if font is "Math".

- lib/ui/imagedecorated.flow
Task https://trello.com/c/GVIw5tYF
> Remove excessive translation inside ImageLabel

- lib/form/paragraph3.flow
- lib/tropic/tropic_paragraph.flow
https://trello.com/c/xqfcViBq/14341-words-are-not-aligned-in-the-categories-title
> Changed the positioning of the text-superscript

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
- lib/tropic/tropic_paragraph.flow
Related PR: https://github.com/area9innovation/innovation/pull/2432
https://trello.com/c/B0wU7ebi/13862-a-non-breakable-space-is-not-working-in-a-math-font-in-the-reader
> Added non-breaking space character support for any content

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
- lib/tropic/tropic_paragraph.flow
Reverts area9innovation/flow9#850
> Revert "Added non-breaking space character support for any content"

- lib/securitymode.flow
https://trello.com/c/p5CeNwKC/59-m2-sensitive-information-obtained
> VerboseOutput

- lib/formats/csv.flow
- lib/formats/csv/csv.lingo-template
New CSV parser implementation using lingo grammar.
> New CSV parser

- lib/material/internal/filebrowser/material_filebrowser_internal.flow
https://trello.com/c/X6B0qlOn/15740-align-input-field-with-label
> Aligned input field

- lib/material/internal/material_player.flow
- lib/material/internal/material_slider.flow
- lib/material/material.flow
- lib/material/tests/test_mvideoplayer_range.flow
https://trello.com/c/dgqAmTfM/793-implement-range-hightlighting-for-mvideoplayer
> MVideoPlayer. Implemented MPlayerHighlightedRanges.

- tools/flow9/backends/bprogram_lower.flow
- tools/flow9/backends/cpp/cpp.flow
- tools/flow9/backends/flowc/flowc.flow
- tools/flow9/backends/js/js.flow
- tools/flow9/backends/koka/koka.flow
- tools/flow9/backends/rename_ids.flow
- tools/flow9/backends/wasm/wasm.flow
- tools/flow9/bexp/bexp.flow
- tools/flow9/bexp/dexp2bexp.flow
- tools/flow9/bexp/pretty.flow
- tools/flow9/bexp/type.flow
- tools/flow9/bexp/utils.flow
- tools/flow9/dexp/implicit_casts.flow
- tools/flow9/dexp/unique_id.flow
- tools/flow9/tests/cpp/structs2.flow
- tools/flow9/tests/type20.flow
> Flow9 : add BCast

- tools/flow9/backends/cpp/cpp.flow
- tools/flow9/tests/cpp/struct_field_print.flow
fix the error: could not convert ‘"name"’ from ‘const char [5]’ to ‘std::u16string’
> Flow9 : u16string fields

- lib/material/internal/filebrowser/material_filebrowser_internal.flow
- lib/material/internal/filebrowser/material_filebrowser_internal_types.flow
https://trello.com/c/OcRjnH91/15175-file-browser-doesnt-apply-a-picture-automatically-after-replacing-a-file?filter=label:Release%202.5
> Added automatically applying of the picture after replacing it.

- tools/flow9/backends/cpp/cpp.flow
- tools/flow9/tests/cpp/maybe_template.flow
> Flow9 : Typars

- tools/flow9/backends/cpp/cpp.flow
- tools/flow9/tests/cpp/strings.flow
@alstrup Is this the right solution to convert all strings to u16string?
> Flow9 : convert all strings to u16string

- tools/flow9/backends/bprogram_lower.flow
- tools/flow9/backends/cpp/cpp.flow
- tools/flow9/bexp/utils.flow
- tools/flow9/tests/cpp/fold_1.flow
- tools/flow9/tests/cpp/fold_2.flow
- tools/flow9/tests/cpp/ignore_return.flow
- tools/flow9/tests/with_main/test3.flow
- native fold
- fix return in sequence
- fix capture
> Flow9 : fold

- lib/flowstructs.flow
- tools/flow9/backends/cpp/cpp.flow
- tools/flow9/backends/cpp/cpp_backend.flow
- tools/flow9/tests/with_main/test6.flow
> Flow 9: native extractStruct (cpp)

- tools/flow9/backends/cpp/cpp.flow
- tools/flow9/backends/cpp/cpp_backend.flow
- tools/flow9/backends/type_hierarchy.flow
- tools/flow9/dexp/types.flow
- tools/flow9/tests/cpp/union_union.flow
> flow9 : union tree

- lib/material/material_color.flow
https://trello.com/c/7YH9PK1D/16264-colour-auto-adjusting-feature-for-table-borders
Related PR:
https://github.com/area9innovation/innovation/pull/2626
https://git.area9lyceum.com/Lyceum/lyceum/pulls/4093
> Refactoring color opacity

- tools/flow9/backends/cpp/cpp.flow
- tools/flow9/backends/cpp/cpp_backend.flow
- tools/flow9/tests/cpp/btree.flow
- tools/flow9/tests/cpp/cast_tree.flow
- tools/flow9/tests/cpp/rec_types.flow
- tools/flow9/tests/cpp/union_union.flow
Before (error):
> struct None{ unsigned int _id = 1;};
>   struct Struct{int32_t flow_v;; Union flow_link; unsigned int _id = 2;};
>   using Union = std::variant<Struct, None>;
After:
s
> truct None{ unsigned int _id = 1;};
> struct Struct;
> using Union = std::variant<Struct, None>;
> 
> struct Struct
> {
>   int32_t flow_v;
>   std::unique_ptr<Union> _flow_link;
>   unsigned int _id = 2;
> 
>   Struct(int32_t _v, Union _link) {
>       flow_v = _v;
>       _flow_link = std::make_unique<Union>(_link);
>   }
> 
>   Struct(const Struct& a) {
>     flow_v = a.flow_v;
>     _flow_link = std::make_unique<Union>(*a._flow_link);
>   }
> };
ds/tree.flow :
Tree<?, ??> ::= TreeNode<?, ??>, TreeEmpty;
TreeNode : (key : ?, value : ??, left : Tree<?, ??>, right : Tree<?, ??>, depth : int);
TreeEmpty …
> Flow9 : recursive types

- lib/tropic/tropic_paragraph.flow
https://trello.com/c/iCrd3JaQ/15043-bug-problem-related-to-the-text-cursor
> Fix cursor position for RTL and paragraph indent

- tools/flow9/backends/cpp/cpp.flow
- tools/flow9/backends/cpp/flow_natives.hpp
- tools/flow9/tests/cpp/flow_type1.flow
- tools/flow9/tests/cpp/flow_type1_2.flow
- tools/flow9/tests/cpp/flow_type2.flow
- tools/flow9/tests/cpp/flow_type3.flow
only type without _cast_
based on std::any, which ~=void*
> Flow9 : flow type

- lib/flowutils.flow
https://trello.com/c/NZO5SHSD
https://github.com/area9innovation/innovation/pull/2662
https://git.area9lyceum.com/Lyceum/lyceum/pulls/4164
> Added function to split int array to array of ranges.

- lib/material/internal/filebrowser/material_filebrowser_internal.flow
Corrected removed files finding process.
https://trello.com/c/VVSr9Ixg/16486-adding-an-image-through-stock-photo-or-upload-immeditaly-shows-the-first-image-in-the-library?filter=label:Release%202.5
> Fixed bug with applying first image in library.

- lib/text/languages.flow
Task : https://trello.com/c/Cgro9bLx/16431-change-the-dialog-to-select-application-language
> Changed native names for several languages

- lib/material/material_ui.flow
prevented bidirectionalLink in multi selection mode
> MDropDownOrAutoSelect in mode autoselect fix

- lib/text/languages.flow
Task https://trello.com/c/kwUrrlP6
> Deutsche -> Deutsch

- lib/flowutils.flow
https://trello.com/c/NZO5SHSD
https://github.com/area9innovation/innovation/pull/2712
https://git.area9lyceum.com/Lyceum/lyceum/pulls/4283
> Changed ids ranges to delta encoding + run length encoding.

- lib/text/translationapi.flow
- lib/text/translationutils.flow
Task https://trello.com/c/OvrBmWa5
> XLIFF: support 'extype' attribute

- lib/fform/fform.flow
- lib/material/material_ui.flow
https://trello.com/c/wkdQsy0C/16497-coach-stops-speaking-when-video-is-fullscreen
> 16497-coach-stops-speaking-when-video-is-fullscreen

- lib/text/languages.flow
Task https://trello.com/c/dmNjCaka
> Remove duplicate languages

- lib/text/translationapi.flow
- lib/text/translationutils.flow
Task https://trello.com/c/IxpaC9Lp
> Xliff: support user-defined attributes

- lib/rendersupport.flow
https://trello.com/c/LWB5jayC/16852-precalculated-subscription-cant-change-signoff-and-missing-skin-id
> fix: loadPreconfiguredFonts

- lib/material/material_color.flow
Related PR: https://github.com/area9innovation/innovation/pull/2632
> Add bitAnd, bitOR for safer opacity operations

- lib/material/extra/calendar/calendar.flow
https://trello.com/c/DQXCSlaE/17718-parent-app-fix-margins-in-calendar-views
> Calendar style to disable horizontal borders

- lib/material/internal/material_expander.flow
- lib/material/material.flow
https://trello.com/c/KhRXnHgi/17671-course-catalog-filter-tweaks
> Added possibility to hide expander icon to "MExpanderIcon" style

- lib/material/internal/material_tree.flow
- lib/material/tests/test_mtree_lazy.flow
https://trello.com/c/N8qnmhxR/17963-search-content-highlight-lo-when-go-to-module
> MTree. MTreeLazyScrollMode. Force item rendering when it is selected.

- lib/material/internal/material_player.flow
- lib/material/material.flow
- Change MPlayerBackgroundOpacity to be transform
> [MVideoPlayer] Add MPlayerDynamicBackground

- platforms/qt/bin/cgi/linux/QtByteRunner.fcgi
- platforms/qt/bin/cgi/linux/lib/libQt5Core.so.5
- platforms/qt/bin/cgi/linux/lib/libQt5Network.so.5
- platforms/qt/bin/cgi/linux/lib/libQt5Sql.so.5
- platforms/qt/bin/cgi/linux/lib/libcrypto.so.1.0.2
- platforms/qt/bin/cgi/linux/lib/libcrypto.so.1.1
- platforms/qt/bin/cgi/linux/lib/libdl.so.2
- platforms/qt/bin/cgi/linux/lib/libfcgi.so.0
- platforms/qt/bin/cgi/linux/lib/libgcc_s.so.1
- platforms/qt/bin/cgi/linux/lib/libglib-2.0.so.0
- platforms/qt/bin/cgi/linux/lib/libgthread-2.0.so.0
- platforms/qt/bin/cgi/linux/lib/libicudata.so.56
- platforms/qt/bin/cgi/linux/lib/libicui18n.so.56
- platforms/qt/bin/cgi/linux/lib/libicuuc.so.56
- platforms/qt/bin/cgi/linux/lib/libmysqlclient.so.21
- platforms/qt/bin/cgi/linux/lib/libpthread.so.0
- platforms/qt/bin/cgi/linux/lib/libresolv.so.2
- platforms/qt/bin/cgi/linux/lib/libssl.so
- platforms/qt/bin/cgi/linux/lib/libssl.so.1.1
- platforms/qt/bin/cgi/linux/lib/libstdc++.so.6
- platforms/qt/bin/cgi/linux/lib/libz.so.1
- platforms/qt/bin/cgi/linux/sqldrivers/libqsqlite.so
- platforms/qt/bin/cgi/linux/sqldrivers/libqsqlmysql.so
- platforms/qt/bin/cgi/linux/sqldrivers/libqsqlodbc.so
- platforms/qt/bin/cgi/linux/sqldrivers/libqsqlpsql.so
Changed libraries to the ones used when compiling
> Rebuild cgi runner with static qt

- lib/net/url_parameter.flow
Task https://trello.com/c/pMsCtuIp
Related changes in lyceum https://git.area9lyceum.com/Lyceum/lyceum/pulls/4931
> Allow to set url parameters from flow

- lib/form/paragraph.flow
- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
- lib/tropic/tropic_paragraph.flow
- lib/tropic/tropic_paragraph_types.flow
Related PR https://github.com/area9innovation/innovation/pull/2876
> Added support for RenderedLinesInfoStyle in TWigify

- lib/text/languages.flow
Task https://trello.com/c/l7RCrcPf
> Languages: add English (Ireland) to common list

- platforms/js/RenderSupport.hx
https://trello.com/c/vwNog5RB/2351-some-wigi-text-doesnt-print
> Fixed printing wigi table.

- lib/string_utils.flow
Checks if all cahracter codes are below 128
> 'isAsciiString' is added to string_utils.

- lib/form/paragraph.flow
I moved _loop1_ into a separate function (breakTextFragmentIntoElements), to help js/html build tail recursion.
https://trello.com/c/oB0AKHrk/18608
> Minor refactoring (breakTextFragment)

- platforms/common/haxe/HaxeRuntime.hx
It was found that toString implementation could be improved in JS, in some heavy usage scenario up to 3 times.
in master:
in branch:
> JS: tune toString

- lib/net/url.flow
- platforms/js/Native.hx
https://trello.com/c/OxINJK7w/18660-downloading-keynote-file-duplicates-tab
> Implemented getUrlAutoclose.

- lib/form/paragraph3.flow
https://trello.com/c/RWC9P4TW/18320-the-mathematical-sign-is-duplicated-on-some-screens
> deleting the duplicate mathematical sign

- lib/material/internal/material_component.flow
- lib/material/material.flow
https://trello.com/c/Ki3gDmlD/18617-impossible-to-delete-custom-module
> MForceTooltipEnabled()

- lib/material/internal/material_datatable.flow
https://trello.com/c/p9dORTLc/2247-rqi-issues-pagination-last-page-looks-broken
> fix behaviour of last_page button in pagination with TScrollEnabled enabled

- lib/material/extra/breadcrumb/breadcrumb.flow
- lib/material/internal/material_grid.flow
- lib/tropic/tflexiblegrid.flow
Added TFlexibleGridMaxContentWidthInspector.
https://trello.com/c/R9fjNt0P/19178-rhapsode-educator-responsiveness-issue
> MFlexibleGrid. Fixed TFlexibleGridContentSizeInspector for RTL.

- lib/runtime.flow
- platforms/js/Native.hx
Task https://trello.com/c/qdZ94IsG
> Introduce preloadStaticResource()

- lib/material/material_colorpicker.flow
Task https://trello.com/c/Vjsl3ETu
> Colorpicker: use localStorage to save recently used colors

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
- lib/tropic/tropic_paragraph.flow
https://trello.com/c/qQVQSwOC/926-alignment-error-with-prime-graphics-in-some-browser
Related PR: https://github.com/area9innovation/innovation/pull/3117
> Fix IgnoreLetterspacingOnReflow style.

- lib/material/internal/material_tabs.flow
- lib/tropic/tropic_gui.flow
Show tabs header shadow on top of the tab background in preview
> Show tab header shadow on top of the tab background in preview

- tools/common/prog_version.flow
- tools/flowc/backends/java/fi2java.flow
- tools/flowc/flowc_version.flow
Now openjdk works as well as oracle java
> Flowc prog version enhanced

- lib/rendersupport.flow
- platforms/js/FontLoader.hx
- platforms/js/RenderSupport.hx
https://trello.com/c/BVY0NOjm/19729-introduce-supporting-a-fixed-layout-in-reader
> Add possibility to load fonts from the file system

- lib/material/internal/material_dialog_internal.flow
https://trello.com/c/lWSrqOyS/20059-fix-the-headings-hierarchy-in-learner
> The renderMDialog3 title is assigned the H2 tag

- lib/material/internal/filebrowser/material_filebrowser_internal.flow
- lib/material/internal/material_list_util.flow
- lib/material/internal/material_pickers.flow
- lib/material/iscript/material_iscript.flow
- lib/material/iscript/material_iscript_dialog.flow
- lib/material/iscript/material_iscript_filter.flow
- lib/material/iscript/material_iscript_form.flow
- lib/material/material_ui.flow
https://trello.com/c/pmxsJLzt/19755-punctuaction-and-capitalization-inconsistencies-in-curator-ui
> Capitalization and punctuation in tooltip

- lib/text/xliffprettyprint.flow
Task https://trello.com/c/nWfPM4oD
> XLIFF: add required attributes

- lib/date.flow
- lib/sys/progressivewebtools.flow
- www/php/stamp.php
https://trello.com/c/YRiG6snx/19878-learner-card-has-start-date-with-no-dates-configured-for-plp
> syncTimeWithServer()

- lib/material/material_print.flow
- lib/material/measing.flow
- lib/material/tests/material_test.flow
- tests/print_test.flow
_card_ : https://trello.com/c/khVP8XFI/2469-book-crash-on-pdfs-creation
> Material print improvement

- lib/form/paragraph3.flow
- lib/tropic/tropic_paragraph.flow
https://trello.com/c/kH4FiwXP/914-twigify-improve-implementation
https://trello.com/c/LTYK2qYE/20368-layout-doesnt-adapt-to-a-screen-when-switches-between-devices-in-simulation
> Wigi: fix endless tropic rendering in some cases

- lib/material/internal/material_app_structure.flow
https://trello.com/c/l9nO5mbB/19671-a-problem-when-swiping-left-from-any-spot-on-the-screen-the-main-menu-will-open
> 19671 a problem when swiping left from any spot on the screen the main menu will open

- lib/fform/fform.flow
- lib/fform/fformmetrics.flow
- lib/fform/fformutils.flow
- lib/fform/optimizefform.flow
- lib/fform/renderfform.flow
- lib/fform/sfform.flow
- lib/material/iscript/material_iscript_form.flow
- lib/material/material_ui.flow
- lib/sys/fullscreen.flow
- platforms/js/AccessWidget.hx
- platforms/js/RenderSupport.hx
Exit from Fullscreen mode issue
https://trello.com/c/GiZvXaqj/20605-scorm-pacakge-in-preview-mode-if-you-zoom-in-scorm-package-will-dissappear
> Mfullscreen no reattachments

- lib/material/internal/material_icons.flow
- lib/material/material.flow
https://trello.com/c/reH9d1yd/19301-request-to-have-the-ability-to-change-the-arabic-ui-numbers-style
> localization of notifications number

- tools/flowc/flowc_find.flow
- tools/flowc/flowc_version.flow
- tools/flowc/symbol_nature.flow
> Added type details to the tooltip;

- lib/date.flow
- lib/math/math.flow
> speed up db2time a bit

- lib/ds/dlist.flow
https://git.area9lyceum.com/Lyceum/lyceum/pulls/6207
> extend dlist lib

- lib/material/material_ui.flow
- Reset current index on destruction
- 20579-reader-double-page-spread-with-custom-audio-coach-only-reads-page-1
> [MMultiAudioPlayer] Add MMultiAudioLength

- lib/runtime.flow
- lib/string.flow
Improved the documentation of some string functions. 
Tested with: 
https://git.area9lyceum.com/Lyceum/lyceum_rhapsode_tests/src/branch/master/flow/test/encoding/encoding.flow
> Improved documentation for string functions

- platforms/js/DisplayObjectHelper.hx
- platforms/js/RenderSupport.hx
https://trello.com/c/UN4U2lOk/21014-scorm-pacakge-in-preview-mode-for-educator-if-you-zoom-in-scorm-package-will-dissappear
> MFullScreenNoReattachments. Render all clips in full screen mode.

- lib/material/internal/material_tree.flow
- lib/material/material.flow
_trello_ : https://trello.com/c/NZ2lZiU5/19291-introduce-an-ability-to-annotate-text-with-multiple-los
_innovation related PR_ : https://github.com/area9innovation/innovation/pull/3278
_lyceum related PR_ : https://git.area9lyceum.com/Lyceum/lyceum/pulls/6244
> [Material Tree] Modify multiselection

- tools/flowc/backends/nim/fi2nim.flow
- tools/flowc/backends/nim/fi2nim_assemble.flow
- tools/flowc/backends/nim/fi2nim_code.flow
- tools/flowc/backends/nim/fi2nim_compile.flow
- tools/flowc/backends/nim/fi2nim_defines.flow
- tools/flowc/backends/nim/fi2nim_types.flow
- tools/flowc/backends/nim/natives/ds/array/replace.nim
- tools/flowc/backends/nim/natives/ds/array/subrange.nim
- tools/flowc/backends/nim/natives/ds/list/list2array.nim
- tools/flowc/backends/nim/natives/ds/list/list2string.nim
- tools/flowc/backends/nim/runtime.nim
- tools/gringo/pflow/interpreter.flow
- tools/gringo/pflow/parse.flow
- tools/gringo/pflow/pflow.flow
- general comparison operator is added. 
- pflow compiles, grammar is parsed successfully.
- some bugs in runtime/compiler are fixed
> Flowc nim comparison

- tools/flowc/backends/common.flow
- tools/flowc/backends/nim/natives/text/binary/fromBinary.nim
- tools/flowc/backends/nim/natives/text/binary/toBinary.nim
- tools/flowc/tests/btester.flow
- tools/flowc/tests/nim/nim_hello.flow
- tools/flowc/tests/nim/test_arrays.flow
- tools/flowc/tests/nim/test_conv.flow
- tools/flowc/tests/nim/test_dynamic.flow
- tools/flowc/tests/nim/test_euler.flow
- tools/flowc/tests/nim/test_http.flow
- tools/flowc/tests/nim/test_httpserver.flow
- tools/flowc/tests/nim/test_lists.flow
- tools/flowc/tests/nim/test_system.flow
- tools/flowc/tests/nim/test_to_string.flow
btester.flow is added to tools/flowc/tests.
This utility runs two backends on a set of tests and compares the output. In case:
- test is compilable on both backends,
- the obtained executable normally finalizes its work,
- the output of both executables are the same
test is considered PASSED.
Otherwise corresponding files with error messages are saved/kept. 
Several tests are added to tests/nim.
> Flowc testing utility

- lib/text/languages.flow
Task https://trello.com/c/quK5p72V
> Add 'Chinese (Traditional)' to the languages list

- lib/date.flow
https://trello.com/c/k0Q9Uggq/21101-gui-translation-arabic-am-pm-1d-loading-user-details-navigation-buttons-for-report-pages
> a.m and p.m. added to the translation

- lib/string_utils.flow
- tools/flowc/backends/nim/fi2nim.flow
- tools/flowc/backends/nim/fi2nim_assemble.flow
- tools/flowc/backends/nim/fi2nim_compile.flow
- tools/flowc/backends/nim/fi2nim_defines.flow
- tools/flowc/backends/nim/fi2nim_transform.flow
- tools/flowc/backends/nim/natives/ds/array/concat.nim
- tools/flowc/backends/nim/natives/runtime/hostCall.nim
- tools/flowc/backends/nim/natives/string/getCharCodeAt.nim
- tools/flowc/backends/nim/natives/string/strlen.nim
- tools/flowc/backends/nim/runtime.nim
- tools/flowc/manipulation/deadcode.flow
- tools/flowc/manipulation/transform_exps.flow
- tools/flowc/tests/btester.flow
- tools/flowc/tests/nim/test_hostcall.flow
- flowc/tests/nim/test_binary compiles to nim
- flowc/tests/nim/test_hostcall passes
> Flowc nim fixes

- lib/form/paragraph3.flow
https://trello.com/c/WNJIUfcL/21135-unnecessay-horizontal-scroll-with-choice-element
https://trello.com/c/ezyoVN68/21134-layout-of-choice-element-in-a-table-is-broken
> Form wigify - fix missed av updates and blowing of hoover

- lib/material/internal/material_datatable.flow
Task https://trello.com/c/k0Q9Uggq
> DataTable: allow to translate tooltips

- lib/ui/fontmapping.flow
Task https://trello.com/c/quK5p72V/21382-add-language-to-content-package-chinese-traditional
> Updated 'isChinese' function

- lib/ui/fontmapping.flow
Task https://trello.com/c/tvHDbHes
> Check content language when selecting font

- lib/string.flow
- lib/text/localization.flow
Task https://trello.com/c/on359Vjn
> Introduce addSoftHyphensIntoWord function

- lib/material/internal/material_datatable.flow
Task https://trello.com/c/GbrgrhT5
> DataTable: fixed pages

- lib/material/internal/material_button.flow
- lib/material/material.flow
https://trello.com/c/8yfg62F8/19634-add-an-option-in-match-probe-to-allow-matching-multiple-answers
> alignment checkBox icon

- tools/flowc/backends/nim/natives/string/fromCharCode.nim
- tools/flowc/backends/nim/natives/string/s2a.nim
- tools/flowc/backends/nim/natives/string/string2utf8.nim
- tools/flowc/backends/nim/runtime.nim
Fix causes passing of test:
// cpp, java, js: [55297]
println(s2a(fromCharCode(55297)));
// cpp, java, js: [0]
println(string2utf8(fromCharCode(0)));
> flowc: nim: some fixes of unicode handling

- lib/render.flow
- lib/ui/fontmapping.flow
https://trello.com/c/LQhoBDJC/22197-reader-custom-fonts-not-supported-with-new1
> Add support for multiple font families

- lib/text/translationsimplestrings.flow
Task https://trello.com/c/Tt5LT9mO
> UI translations: Don't always add 'nocache=' parameter

- lib/text/readability.flow
https://trello.com/c/e9Il7rfT/22374-revisit-readability-calculations-under-the-module-summary
> 22374-revisit-readability-calculations-under-the-module-summary

- platforms/js/TextClip.hx
https://trello.com/c/qGOYSVQF/22209-review-loading-too-long
> JS. TextClip. Added optimization for japanese font measurements.

- lib/string.flow
task https://trello.com/c/G9iuNI4x
> strReplace with case insensitive search of a substring

- lib/fform/fform.flow
- lib/material/material_ui.flow
Task https://trello.com/c/rT2OZ5wO
> Introduce new style MMultiAudioTimerange

- lib/string.flow
- make comments clearer;
- get rid of doStrSplit2;
- fix strSplitLeave case with empty separator;
without any change in functionality
> strSplit refactoring

- lib/text/translation.flow
Task https://trello.com/c/3Ixy4ClH
This reverts commit 8bd10a080e327687594444055ec9fe917c867a83.
> Revert "Run doReplacement only if translated string is equal to source (#350)"

- lib/text/languages.flow
Task https://trello.com/c/CwAxxNZl
> Rename 'Brazilian Portuguese'

- lib/form/paragraph3.flow
- lib/form/paragraphtypes.flow
- lib/text/bidi_text.flow
- lib/text/unicodecharacters.flow
- lib/tropic/tropic_paragraph.flow
https://trello.com/c/39nB8lKN/23129-line-break-in-reader-doesnt-work-properly-lines-are-cut-off
> Fix line breaks and overlapping text for content containing non-breaking spaces

- lib/rendersupport.flow
Task https://trello.com/c/Gh2lxCo6
> Introduce new 'hadUserInteracted' property

- lib/tropic/tropic_paragraph.flow
https://trello.com/c/2bBn5Kzm/19735-wrong-words-order-in-wigi-paragraph-tropic-mode
> Tropic. Fixed dynamic words order in DOM

- lib/tropic/tropic_paragraph.flow
https://trello.com/c/rJKQQ85h/941-optimizing-the-rendering-of-tropic-paragraphs-with-dynamic-elements
> Execute reflow after all sizes have been calculated

- lib/tropic/tscroll.flow
https://trello.com/c/3sHvxYMu/23265-scroll-bar-overlapping-items-in-profile-settings
> Fix horizontal scroll gap

- lib/formats/html/html2form.flow
https://trello.com/c/fTFeHeVM/19718-mobile-view-fix-swiping-in-forums
> Prevent clicking on image if it's scrolling

- lib/lingo/flow/bytecode.flow
- platforms/common/cpp/core/ByteCodeRunner.cpp
- platforms/qt/bin/linux/QtByteRunner
- platforms/qt/bin/windows/QtByteRunner.exe
- tools/flowc/desugar.flow
- tools/flowc/flowc_version.flow
- tools/flowc/tests/optimize/out/lingo_flow_bytecode.flow
Allow a structure to have 65536 fields (instead of 256 before).
<details><summary>Test case: </summary>
```flow
import runtime;
StructMix(
field1 : int, field2 : string, field3 : double, field4 : Maybe<int>, field5 : Maybe<string>, field6 : Maybe<double>, field7 : Maybe<int>, field8 : Maybe<string>, field9 : Maybe<double>, field10 : int,
field11 : int, field12 : string, field13 : double, field14 : Maybe<int>, field15 : Maybe<string>, field16 : Maybe<double>, field17 : Maybe<int>, field18 : Maybe<string>, field19 : Maybe<double>, field20 : int,
field21 : int, field22 : string, field23 : double, field24 : Maybe<int>, field25 : Maybe<string>, field26 : Maybe<double>, field27 : Maybe<int>, field28 : Maybe<string>, field29 : Maybe<double>, field30 : int,
field31 : int, field32 : string, …
```
> Updated bytecode format

- lib/material/internal/material_focus.flow
https://trello.com/c/ZKpBQYEa/23317-issues-in-mobile-tablet-match-and-categorize-probes
> focus fixing

- lib/material/internal/tropic_size_util.flow
- lib/material/material_gui.flow
- lib/material/tests/test_first_second_helpers.flow
https://trello.com/c/kOC8m9ed/816-implement-byfirst-bysecond-helpers-family
See test_first_second_helpers.flow for testcase
> Implemented *ByFirst/*BySecond helpers family

- lib/material/internal/material_player.flow
- lib/material/material.flow
Related Trello card: https://trello.com/c/dcMFzeBp/3385-improvements-when-printing-video
Related PR: https://github.com/area9innovation/innovation/pull/3684
> [Media Player] Style to add a custom control button in media player

- tools/flowc/desugar.flow
- tools/flowc/flowc_version.flow
- tools/flowc/type_helpers.flow
Multiple struct / union definitions are not allowed.
> Flowc fix multy struct defs

- lib/tropic/tflexiblegrid.flow
https://trello.com/c/IPHYYsQH/24024-multiple-alignment-issues-in-categoriz-probes
> fixed position of items in TFlexibleGrid

- lib/tropic/tropic_paragraph.flow
https://trello.com/c/gEw1udQd/951-mindflow-crash-in-the-property-panel
> Fix reflow crash

- lib/material/internal/material_tabs.flow
https://trello.com/c/zG7EOBhK/23944-misleading-pointer
> changed CursorShape for tab panel

- lib/material/measing.flow
- lib/tropic/tropic.flow
Related Card : https://trello.com/c/8CbukakR/3501-introduce-a-negative-zoom-for-background-images
Related PR: https://github.com/area9innovation/innovation/pull/3755
> Remove MZoomAnimation from lib, fix TFillZoom comment

- lib/material/material_print.flow
Related PR: https://git.area9lyceum.com/Lyceum/lyceum/pulls/8088
> Add style to enable/disable print button in ShowMPrintPagesDialog

- lib/ds/array_diff.flow
don't calculate operations, if arrays are equal
@alstrup  is it safe to merge PR? what should i test?
> arrayDiff : edge case (equal arrays)

- lib/tropic/tflexiblegrid.flow
> fixed tflexiblegrid for items with zero height or width

- lib/material/internal/material_pickers.flow
- lib/material/internal/material_util.flow
> fixed color picker

- lib/sys/platformevent.flow
for this feature - https://git.area9lyceum.com/Lyceum/lyceum/pulls/8240
> style for active time counter

- lib/material/internal/material_dialog_internal.flow
https://trello.com/c/bAUOLKTK/24599-allow-educators-to-leave-notes-and-tag-learners
> add MDialogMinSize and MDialogMaxSize to MDialogStyle

- lib/material/extra/calendar/calendar.flow
> Calendar: added new week view for calendar

- lib/tropic/tropic_paragraph.flow
https://trello.com/c/TdkLecza/25127-reader-is-rendered-incorrectly-the-first-time
> Add GeneralDynamicSpace to dynMetricsSubscription

- lib/material/extra/calendar/calendar.flow
Add CalendarSelectedTab to enable external management of the selected tab
> CalendatForEvents. Added CalendarSelectedTab

- lib/material/internal/material_tabs.flow
- lib/material/material.flow
Trello: https://trello.com/c/sRIO4RAw
Related PR: https://github.com/area9innovation/innovation/pull/3896
> [Tabs] Introduce ability to set a custom header color when tab is selected

- lib/formats/html/html2form.flow
- lib/formats/json/json.flow
Task https://trello.com/c/gCvynpWQ/25311-when-zoom-is-enabled-allow-zoom-when-clicking-on-image-not-only-clicking-on-the-small-icon
> Images: allow zoom when clicking on image, not only clicking on the small icon

- lib/fform/fformutils.flow
> tune renderFAnimation

- lib/formats/html/html2form.flow
Task https://trello.com/c/gCvynpWQ
> Images: allow to zoom image by clicking if there was no movement

- lib/material/internal/material_focus_util.flow
- lib/material/internal/material_player.flow
- lib/material/internal/types.flow
- lib/material/material_manager.flow
Task https://trello.com/c/w12OFjjg/25411-stop-media-of-lr-after-opening-another-lr-from-map
> Allow pausing all running video players

- lib/tropic/tropic_paragraph.flow
https://trello.com/c/Tc94RwTM/25456-issues-with-text-alignment-when-clicking-on-shiftenter
> Don't justify lines with NewLine ends

- lib/material/material_gui.flow
> MFrameCustomA()

- lib/material/internal/material_player.flow
- lib/material/material.flow
- lib/ui/videoplayer.flow
task https://trello.com/c/9CUSXK7o
> Videoplayer: support tts:textAlign attribute

- lib/tropic/tropic_paragraph.flow
- lib/tropic/tropic_paragraph_types.flow
https://trello.com/c/UG7DbN5t/25300-the-text-extends-beyond-the-frame
> TRenderParagraph. Update on text width changed.

- platforms/js/FlowSprite.hx
- platforms/js/RequestQueue.hx
- platforms/js/VideoClip.hx
Optimization to load a single image/video/audio only once.
> added cache and queue for media downloads

- lib/form/form.flow
- lib/rendersupport.flow
- platforms/js/FlowSprite.hx
- platforms/js/RequestQueue.hx
- platforms/js/VideoClip.hx
https://trello.com/c/uDfCkAdG/25898-images-keep-loading-when-scrolling
Paired with
https://github.com/area9innovation/innovation/pull/3998
https://git.area9lyceum.com/Lyceum/lyceum/pulls/8798
> JS. FlowSprite. Keep in request cache after loading.

- lib/fform/renderfform.flow
- lib/form/renderform.flow
- lib/net/picutil.flow
- lib/render.flow
Due to new feature which removes tokens from the url - updated the caching of picture size
> new methods to cache size, refactoring

- lib/formats/css/parse_css.flow
- lib/formats/css/stylesheet.flow
https://trello.com/c/9svkL6rn/25938-improve-quality-of-arabian-epubs-converted-in-a-fixed-layout
> change default alignment

- lib/password.flow
- platforms/java/com/area9innovation/flow/FlowPassword.java
In fact - copied from security.php
> implemented validation string operations in java target.

- lib/form/paragraph.flow
- lib/text/localization.flow
https://trello.com/c/rVGNhHy5/25990-missed-symbol-in-rtl
> Fix hyphens in arabic

- lib/formats/xml.flow
https://trello.com/c/1dKWg2tB/26390-add-supporting-audio-files-from-epubs-to-be-able-to-play-them-clicking-on-an-icon-on-a-page
> add function for determination tag type

- platforms/common/haxe/HaxeRuntime.hx
Task https://trello.com/c/uZYKTSsQ/26388-prohibit-special-symbols-in-external-service-key
> json: encode symbols 0x80-0xFF

- lib/formats/xml.flow
https://trello.com/c/1dKWg2tB/26390-add-supporting-audio-files-from-epubs-to-be-able-to-play-them-clicking-on-an-icon-on-a-page
> add generateHasSpecificAttributeValueFn function

- platforms/common/haxe/HaxeRuntime.hx
This reverts commit 8bb09ecdabbefac75c16912a0ae851db03cede0c.
> Revert "json: encode symbols 0x80-0xFF (#1414)"

- lib/material/internal/material_grid.flow
Related to: https://trello.com/c/DYwELusA
> Make usable TOrder style for MFlexibleGrid

- lib/fform/sfform.flow
- lib/formats/css/parse_css.flow
- lib/formats/css/stylesheet.flow
- lib/formats/html/form2html.flow
- lib/render.flow
- lib/stylestructs.flow
- lib/tropic/tropic_ui.flow
- platforms/js/RenderSupport.hx
- platforms/js/TextClip.hx
https://trello.com/c/9svkL6rn/25938-improve-quality-of-arabian-epubs-converted-in-a-fixed-layout
> add font-feature-settings

- lib/form/gui.flow
https://trello.com/c/X5jtz27A
**Related PR:** https://github.com/area9innovation/innovation/pull/4112
> Fix rendering loop of table with images.

- lib/tropic/tropic_paragraph.flow
https://trello.com/c/OVPq0oKJ/26684-immortal-annotation-in-reader
> TropicParagraph. Hide truncated annotated space

- lib/formats/html/html2form.flow
- lib/ui/videoplayer.flow
https://trello.com/c/iY4GjrL2/956-epub-to-reader-formatting-in-tables-is-inconsistent
> html2wigi fix for tables

- lib/rendersupport.flow
- platforms/js/RenderSupport.hx
Task https://trello.com/c/hrfn5zao/26748-browser-translation-tool-is-offering-to-translate-webpage-and-shouldnt
> Ability to set the 'translate' attribute

- lib/material/internal/filebrowser/material_filebrowser_internal.flow
https://trello.com/c/mmCW7bBC/26850-add-create-and-open-button-into-filebrowser-create-folder-menu
> add CREATE AND OPEN button

- lib/material/internal/material_button.flow
> Fix caption for radio group

- lib/material/internal/filebrowser/material_filebrowser_internal.flow
- lib/material/internal/filebrowser/material_filebrowser_internal_view.flow
- lib/material/material_dialog.flow
https://trello.com/c/dbSC6YNP/26870-add-create-and-open-button-into-files-view-create-folder-menu
> add ShowMDialogForFolderWithCallbacks

- lib/material/internal/material_dialog_internal.flow
https://trello.com/c/MIoD662Y/26867-improve-ux-for-match-popup
> add MDialogSideBorder and MDialogContentMinWidth to MDialogStyle

- lib/rendersupport.flow
- platforms/js/RenderSupport.hx
Task https://trello.com/c/lj8vEIP7/26755-collins-native-app-fix-zoom-glitches
> Access to the viewport tag content

- lib/material/internal/material_textinput.flow
- lib/material/internal/material_textinput_state.flow
https://trello.com/c/RwAiS19i/26805-clear-search-field-is-not-keyboard-accessible
> Fixed: Clear search field is not keyboard accessible

- lib/fusion.flow
https://trello.com/c/5McDPEN6/26703-learner-crashes-on-iphone-safari-or-chrome
> WIP: doFuseDynamic tune memory usage

- lib/material/internal/material_player.flow
- lib/material/material.flow
https://github.com/area9innovation/innovation/pull/4163
> [MVideoPlayer] Add MPassClicks

- lib/material/internal/material_slider.flow
- lib/material/material.flow
https://trello.com/c/3katnL98/20817-improve-wigi-slider-element
> Introduce increaseSize option

- lib/material/internal/material_slider.flow
https://trello.com/c/3katnL98/20817-improve-wigi-slider-element
> Adjust slider width to fit captions

- lib/material/material_gui.flow
https://trello.com/c/cm2bOLP2/810-implement-segmented-buttons
Segmented buttons: 
https://m3.material.io/components/segmented-buttons/overview
> Added helper for creating segmented buttons

- lib/material/internal/material_steppers.flow
- https://trello.com/c/xxSNR8xG/3707-stepper-element-doesnt-adapt-to-a-panel-size-when-switches-between-steps
> [Material] Stepper: Make footer adaptive

- lib/fusion_utils.flow
- lib/material/material_ui.flow
> speedup MLazyList

- lib/material/internal/filebrowser/material_filebrowser_internal.flow
https://trello.com/c/YjdKkFeI/25070-slideshows-make-it-possible-to-mirroring-background-images-in-decoration-panel
> add icon eye in filebrowser dialog menu when image is selected

- lib/material/internal/material_menu.flow
https://trello.com/c/oS2MqpNI/27349-change-the-font-opacity-of-the-filters-sorting-and-show-hide-on-the-dashboard
> Added the ability to set transparency for MDropDownIcon

- lib/material/internal/material_slider.flow
- lib/material/material.flow
> Introduce MSliderAreaWidthInspector style

- platforms/js/HttpCustom.hx
Browser (Chrome Version 136.0.7103.93) does not allow to get responses longer than 512M using XMLHttpRequest().responseText
After this fix:
Now we can at least find the error in the console.
> Print an error due to a large response

- lib/formats/css/parse_css.flow
- lib/formats/css/stylesheet.flow
https://trello.com/c/9svkL6rn/25938-improve-quality-of-arabian-epubs-converted-in-a-fixed-layout
> add isDirectionRTL field to CssStyle structure

- lib/tropic/tropic_paragraph.flow
https://trello.com/c/DeP49eRY/539-ilearn-curator-text-gets-trimmed-when-on-a-new-line-depending-on-screen-size-glpi-2125-pt-110112
> TropicParagraph. Do not trim and detach underlined spaces.

- lib/tropic/tropic_paragraph.flow
- lib/tropic/tropic_paragraph_types.flow
https://trello.com/c/5rXTuXeR/28428-alignment-of-hyperlinks-within-phrase-with-high-relevance-for-translations-needs-an-improvement-hempel
> Allow focus on first word only

- platforms/js/TextClip.hx
https://trello.com/c/5jLsxylu/28362-invisible-image-gets-focus-of-sr
> hide element for SR

- lib/material/internal/material_slider.flow
- lib/material/material.flow
https://trello.com/c/PhIJb0Av/28500-coach-submenu-issues
> add MSliderInputOnKeyDown to MSliderStyle

- lib/material/tests/test_split.flow
- platforms/js/Native.hx
For the sake of educator loading optimization attempts. https://trello.com/c/wARk8FE2/26351-educator-lite-mode
@tupieurods compared flow-based and native implementation, the latter one has a gain of ~1s on the large text.
> Added native strSplit in Haxe.

- lib/material/internal/material_steppers.flow
- lib/material/material.flow
- lib/material/tests/msteppers_test.flow
new style. for Vertical type only (in PR)
> MStepperContentFrame

- lib/material/internal/material_dialog_internal.flow
https://trello.com/c/OEcDEwwV/27072-feedback-pop-up-text-isnt-announced-by-sr
> add "aria-labelledby" for snackBar

- platforms/js/Native.hx
https://github.com/area9innovation/innovation/pull/4424
it improves the performance of list2array operation - in general and in case we know the size of the list in advance
> Normalize wigi tune - list2array & list2ArrayWithCount
