area9innovation/flow9

lib/string.flow, platforms/java/com/area9innovation/flow/Native.java
This PR reduces amount of GC, produced by string operations `strGlue()` and `list2string()`.
These two produce literally gigabytes of garbage during its work.
In this PR functions logic remains the same, while memory consumption significantly reduced.
=> Reduce garbage amount for string operations

lib/sys/target.flow
Task https://trello.com/c/k4zJ1ywz/4747-safari-mac-loads-video-and-coach-speech-too-slowly-in-one-slide
=> show video as button in safari too

lib/material/internal/material_dropdown.flow, lib/material/internal/material_menu.flow, lib/material/material.flow, lib/material/material_ui.flow, lib/material/tests/test_dropdown_or_autocomplete.flow
When there are a lot of items in MDropDown it starts to hang, works slow. The idea is to use MAutoComplete if the count of items more set limit.
Introduced code is already used mainly in customdb component. If it's OK to move the code to Material like this, the customdb code will be removed.
=> MDropDownOrAutoComplete

lib/pebbles/pebble_parameters.flow, tests/pebbles_bug.flow
Added test case shows that if PebbleStringLink uses encoded string as the valueB, it leads to a double call of onChange function inside changeParameterValue.
Using urlDecode(value) seems to me the logical solution. But I'm not sure wouldn't it break something.
=> Added urlDecode to MSelectPebbleParameters

tools/common/compilerconfig.flow
This allows to use the default fontconfig from `resources/`, even when it's not specified in flow.config.
I'm not sure if I should recompile any binaries, so would be glad for some tips. Thanks!
=> Use absolute path to default fontconfig in resources

lib/ds/array_diff.flow, lib/material/internal/material_tabs.flow, lib/tropic/selecttarray.flow, lib/tropic/tropic_array.flow
test app:
in the master, we can't use protocol obtained from arrayDiff because it was reversed inside and attempt to apply it to the source array would lead to the wrong result
```
import ds/array_diff;
printInfo(title : string, arr : [?]) -> void {
println(title + ":");
iteri(arr, \i, a : ? -> println("  " + lpad(i2s(i), " ", 3) + " " + toString(a)));
}
main() {
source = ["The", " ", "boy", " ", "walked", " ", "down", " ", "the", " ", "street", "." ];
target = ["The", " ", "boy", " ", "is", " ", "walks", " ", "down", " ", "the", " ", "street", "." ];
printInfo("source", source);
printInfo("target", target);
protocol = arrayDiff(source, target, false);
printInfo("protocol", protocol);
applyProtocol = \theSource, theProtocol ->
fold(theProtocol, theSource, \acc, op -> {
switch (op : …
```
=> arrayDiff: remove reverse and fix tests

lib/form/paragraph.flow, lib/form/paragraph3.flow, lib/form/paragraphtypes.flow, lib/formats/html/html2form.flow
In edit mode, wigi traverse interactive elements (IE) list made from paragraph in order to find the real position of the cursor on the screen. but reflow procedure removes last space on the each line that does not fit the width so such IE does not recieve updates of it's coordinates and the positionin of the cursor gets wrong.
We can't just keep such spaces because it would lead to horizontal scroll appear and we can't put them on the next line because it will break align.
So we have to introduce attach/detach property for the words.
=> wigi: we should track detached words for cursor related stuff

lib/material/internal/mstring.flow
Sometimes js code in the browser encountered such an error.
Uncaught RangeError: Maximum call stack size exceeded
Locally, I checked and everything was decided if to avoid recursion
=> Fix for recursive containsHanScript

lib/ui/imagedecorated.flow
I have provided deep code investigation and noticed that size of decorated forms is not used anywhere.
There is only one place where it's used and it's lead to bug of decreasing image sizes after zoomming. So, I have removed these sizes.
@ViktorKurach Could you please, check if your project is not broken with this branches?
https://github.com/area9innovation/innovation/pull/773
=> Remove size inspecting from decorations forms, because size is unused

lib/math/math.flow
When I see a function like fn(value : double) -> double, I expect it works actually with doubles and doesn't miss a huge range of data that's out of intMin - intMax.
What if we do the change, would it break something?
=> dceil and frac - use full values range, not only integers

lib/form/adaptivescale.flow
Since smart options were moved to /smartbuilder code, we need a way to set useMobileUI() function to true in CCL when corresponding smart option is set.
goes with: https://github.com/area9innovation/flowapps/pull/807
=> Adding way to use useMobileUI in CCL

platforms/js/Native.hx
test:
> 	timeit(\ -> {
s = "Hello World";
generate(0, 100000, \__ -> {			
string2utf8(s) |> ignore			
}) |> ignore
}) |> println;
shows 98 ms instead of 189 ms in average
=> Get rid of BytesOutput

platforms/js/JsMd5.hx, platforms/js/Native.hx
Removed haxe.io.Bytes.ofString because it was using Array without predefined size.
Encoding conversion code in JsMd5 is based on this part https://github.com/HaxeFoundation/haxe/blob/3.4.7/std/haxe/io/Bytes.hx#L523-L547
Which is haxe.io.Bytes.ofString.
And removed blocks array allocation from MD5 implementation. We don't need more than 64 bytes at a time for a single round - so no need to precompute all of them.
I didn't benchmark old and new implementation yet in terms of speed. But version from this pr doesn't produce extra memory overhead. And this was our original issue.
=> Haxe js md5 port

lib/net/http_request_util.flow
Required for Trello card:
https://trello.com/c/3mBgptzZ/6437-invalid-link-url-in-invitation-emails
Add functions that convert a list of `KeyValue`s to a string in format
`application/x-www-form-urlencoded`
=> Implement serializing KeyValues for use in URLs

lib/material/internal/material_pickers.flow
@NikitaFil can you please approve this changes?
Changes made according to card: https://trello.com/c/I9eTFawW/1026-add-transparency-heading-before-the-slider-in-the-color-picker
=> add heading before opacity slider in opacity picker

lib/form/paragraph3.flow, lib/form/paragraphtypes.flow, lib/tropic/tropic_paragraph.flow
used in https://git.area9lyceum.com/Lyceum/lyceum/pulls/877
**Test case**:
1) run curator with duration=0 and dev=1
2) create several (5 or more) Slide in different LO in module with the wigi doc below.
3) test the module with fast press to "cake"
4) observe that the line of text blinks
it happens because the text is rendered with first form of CalcCell that has 0 width, and then when the cell gets the values it width increased but the reflow of the paragraph that places texts and updates the coordinates of the CalcCell is deferred and happens later.
```
WigiStory(ref [WigiParagraph([WigiText("some text ", []), WigiBlock(WigiExternalBlock("material_calculated_cell", TreeNode("varName", "var_name_1", TreeNode("formula", "= a", TreeEmpty(), TreeEmpty(), 1), TreeNode("wigiName", …
```
=> wigi renderParagraph: refactor and introduce setting paragraphDynamicBlockDelay

lib/pebbles/pebble_hierarchy.flow
This is to reach 2 goals:
1) include in pebble hierarchy items with parameter names already in use which we should not change because they are used in notification emails being sent.
2) keep hierarchy parameters in a view sequence like this
v1 -> v3 -> v2 
where v1, v2 use chips and hierarchy filtering 
but v3 uses breadcrumbs and do not need the hierarchy filtering
=> pebbles - allow custom hierarchy item name and ability to hide chips

lib/text/languages.flow
Now we have "English" (it means English US) and English UK
=> no en-US is needed

lib/form/virtual_screen_types.flow, lib/formats/html/html2form.flow
We need to use special render function to display popups in wigi, not just render(...).
Popups shouldn't be on top of everything else, only above virtual screen.
=> Image zoom is broken in Learner in Simulate

lib/algorithms.flow
Binary search didn't handle the case with insert second (in front or at the end of array).
Here's a gist with a test case: https://gist.github.com/Undiy/f0f1c1e4e6dc34e694d685b0e0b71e1b
=> binarySearch fix

lib/form/paragraph3.flow
https://trello.com/c/Lsdc8Xpt/7588-extra-line-break-is-added-in-simulate-between-bullet-and-text-for-narrow-columns
=> Fixed extra line break not to be added in Simulate between bullet and text for narrow columns

platforms/js/TextClip.hx
In some cases,  glyphs used to draw text on the screen are changed by getActualGlyphsString. In this case we have to measure metrics for TextClip using the same set of glyphs or the result could be wrong
**in the branch without calculation of metrics by HTML**:
**in the master without without calculation of metrics by HTML https://github.com/area9innovation/flow9/commit/a0fe170ba8ccd136c8f4d422f843afcc18297c01**:
```
import wigi/utils;
main() {
setLang("ar");
setDefaultRhapsodeFontMappingFn();
// with this enabled baseline alignement works wrong
if (isUrlParameterFalse("dom")) setRendererType("canvas") else setRendererType("html");
arabic1 = "لوصف هذه البلاد في العصور";
//	arabic1 = "العصور";
fontSize = 32.;
pMDebug = \color -> \m -> MDebug(color, m);
makeText = \str, family, doSplit -> { …
```
=> TextClip: text and nativeWidged.textContent should be in sync

platforms/js/FlowFontStyle.hx, platforms/js/TextClip.hx
Scheherazade remapped using getActualGlyphsString  into glyphs that are not supported by the font so we just disable remapping as hot fix.
in the fontconfig.json we will write:
```
"Scheherazade": {
"family": "Scheherazade Regular",
"weight": 300,
"style": "normal",
"doNotRemap" : true
},
"ScheherazadeBold": {
"family": "Scheherazade Bold",
"weight": 900,
"style": "normal",
"doNotRemap" : true
},
"ScheherazadeItalic": {
"family": "Scheherazade Regular",
"weight": 300,
"style": "italic",
"doNotRemap" : true
},
"ScheherazadeBoldItalic": {
"family": "Scheherazade Bold",
"weight": 900,
"style": "italic",
"doNotRemap" : true
}
```
in the branch:
in the master:
=> hot fix for wrong getActualGlyphsString for some fonts

platforms/js/FontLoader.hx
Now we can specify which test strings should be used for every font.
for example, in fontconfig.json we can write:
```
"webfontconfig": {
"google": {
"families": [
"Material Icons",
"Roboto:300,500,300italic,500italic",
"Amiri:400,600,400italic,600italic"
],
"testStrings": {
"Amiri" : "العصور"
}
},
"custom": {
"families": ["Dubai Regular", "Dubai Bold", "Scheherazade Regular", "Scheherazade Bold"],
"urls": ["fonts/fonts.css"],
"testStrings": {
"Dubai Regular" : "العصور",
"Dubai Bold" : "العصور",
"Scheherazade Regular" : "العصور",
"Scheherazade Bold" : "العصور"
}
}
},
```
=> FontLoader: add support for custom text strings

lib/pebbles/pebble_utils.flow
We don't need to change the itemsB : DynamicBehaviour inside these functions, but just fgetValue of it.
Also, I need to call these functions using result of 
fselect2(DynamicBehaviour<>, DynamicBehaviour<>, FLift2(...)) as argument, it will looks fine in my code and I would not create unnecessary unsubscribers for it.
But compiler didn't allowed me to do this.
Do you have any objections for this changings?
=> Need to change DynamicBehaviour to Transform in some function arguments for pebble_utils

lib/fform/fformutils.flow, lib/material/tests/test_mtext.flow
Suggestion to fix texts overlapping when EscapeHTML(false) is used.
Before : 
After :
=> renderFTexts. Fix text parts overlapping.

lib/formats/html/html2form.flow
I am in doubt ... Can I change the current function? (Or create a new one? :( )
https://trello.com/c/MdQ2jQv7/8471-images-always-allow-zoom-although-option-is-disabled#comment-5e3a906e2b470d724e411037
=> show zoom icons on small screens

lib/material/internal/material_splitter.flow
https://trello.com/c/cqteTD3r/7749-cursor-does-not-change-when-moving-view-splitter-in-curator-todos
=> Fix cursor for MSplitter

platforms/qt/qt-backend/CgiSupport.cpp
This fix is intended to make code like
iter(...., \ -> doQuitOnSomeCondition);
quit(0);
work properly. Now such code always returns 0.
=> Fixed 'quit' native for cgi

lib/fform/renderfform.flow, lib/fform/sfform.flow, lib/form/form.flow, lib/form/renderform.flow, lib/rendersupport.flow, platforms/java/com/area9innovation/flow/RenderSupport.java, platforms/java/javafx/com/area9innovation/flow/javafx/FxRenderSupport.java, platforms/js/RenderSupport.hx, platforms/js/RenderSupportNodeJs.hx, platforms/js/WebClip.hx, tools/flowc/backends/cpp/flow_rendersupport.hpp
IFrame shows horizontal scroll unpredictable depending on it's internal logic of re-flowing of words.
this PR allows to set special style to instruct MRealHTML to hide the horizontal scroll.
required for https://github.com/area9innovation/innovation/pull/1519
In master:
in branch:
=> RealHtml: introduce RealHtmlHideHorizontalScroll style

lib/form/paragraph3.flow, lib/tropic/tropic_paragraph.flow
https://trello.com/c/6B3yEwAM/570-service-to-insert-soft-hyphenation-in-a-text
Previous comparison was inconsistent. The comparison was made for text w/o hyphens vs. text with hyphens.
New comparison is made for text with hyphens. On master branch w/o solution applied using Chrome profile minimum time obtained (ms): reflowTParaWords - 1.3, reflowTParaWordsRec - 1.1. This is on parity with the time when the latest solution is applied.
For testing used: https://github.com/area9innovation/innovation/blob/master/sandbox/test_reflowParaword_hyphen.flow
=> Showing hyphenation in dynamic paragraph - fixed wigify, optimized solution for editor

lib/material/material_gui.flow
https://trello.com/c/WswXBPhI/793-probe-stem-text-box-container-is-larger-than-the-screen-causes-horizontal-scrolling
=> MZoomToFit() fix for fillers

lib/fform/fform.flow, lib/form/optimizeform.flow, lib/formats/html/form2html.flow, lib/stylestructs.flow, lib/tropic/tropic_ui.flow
It was found out that the following code is incorrect 
https://github.com/area9innovation/innovation/blame/master/lib/wigi/wigify.flow#L1227, because CharacterStyle doesn't contain FSetDirection. This causes crashes in https://github.com/area9innovation/flow9/blob/master/lib/form/optimizeform.flow#L309
This change fixes this. Maybe it's worth to rename FSetDirection to SetDirection.
=> Extended CharacterStyle to contain FSetDirection

platforms/js/FlowFileSystem.hx
https://trello.com/c/OM0aYCKj/9362-deploying-packages-in-safari-corrupts-the-content
Safari replaces two-chars symbol  å (a&#x30a;) to one char å (&aring;)
it breaks fjson because of the length changes
this PR replace such symbol with extra zero-width space symbol
=> Fix https://trello.com/c/OM0aYCKj/9362-deploying-packages-in-safari-corrupts-the-content

lib/net/http.flow, lib/net/http_types.flow
UploadSelect's result uses as a condition for calling the uploadClientFile().
- true: call uploadClientFile();
- false: use the callback of UploadSelectUnfit for tell the user why that file doesn't fit.
I'm not sure about the naming of UploadSelectUnfit structure.
=> 'UploadSelect' for uploadFile function

lib/ui/fontmapping.flow
https://trello.com/c/Oaix9Pie/9259-scheherazade-standard-font-size-is-very-small-the-default-font-size-should-be-19-to-be-equivalent-to-tahoma-14
Before 
After
=> Fixed Scheherazade standard font size is very small

lib/formats/json/json.flow
There is a strict check for `e` but sometimes it is `E` and it works the same way.
Without this change 0E-8 will cause an error.
=> json double with E parsing fixed

lib/form/paragraph3.flow, lib/ui/fontmapping.flow, platforms/js/TextClip.hx
JS target solution only. Non-breaking space no more LTR character in Haxe TextClip natives, alphabet direction function added, improved metrics for Arabic word parts via fooling pixijs.
Linked PR: https://github.com/area9innovation/innovation/pull/1808.
=> https://trello.com/c/I6eDHyd5/10503-cursor-issue-arabic

lib/ds/arrayutils.flow
padArray(), as stated in its description (https://github.com/area9innovation/flow9/blob/master/lib/ds/arrayutils.flow#L58), is supposed to fill the given array till the given length but instead it adds the given length to the initial length.
=> padArray() fix

platforms/js/RenderSupport.hx, www/flowjs_debug.html, www/js/webfont_debug.js
we will be able to use flowjs_debug.html file that will load webfont_debug.js with all names and structure preserved.
=> WebFont: add debug version and add output of total web font loading time to console

tools/flowc/flowc_lsp.flow, tools/flowc/flowc_remote.flow, tools/flowc/flowc_server.flow, tools/flowc/flowc_version.flow
Solution to: https://trello.com/c/CscV560c/735-flowc1-wrong-fontconfig-file-is-taken-in-in-server-mode
=> Flowc fontconfig relative path

lib/ui/fontmapping.flow
We need to set default font family from the app.
We will use it to set the font from a rhapsode skin property.
=> fontmapping: add setFontFamilyOverride

lib/formats/html/form2html.flow
gmail removes styles completely if something is incorrect inside.
before
after
=> don't add empty style

platforms/js/Native.hx
measured using http://localhost/rhapsode/flowjs.html?name=learner&new=1&compacting=0&i=yegor.dovganich@area9.dk#home
final point is Dashboard screen after all activities are completed and GC collects garbage
compactJson does not give any measurable improvments.
string table cache on object2JsonStructs level does improve (Safari, MacOS):
final memory usage in the same test reduced from 361-371 down to 293-295 Mb
Peak memory uage reduced too from 842-847 down to 721-755 Mb
https://trello-attachments.s3.amazonaws.com/5a4a73d7f5ecb00ce1364e40/5f0f28a54b14f43d974a5260/635c19ff518e29384eebd6ba2a64c1ce/image.png
Chrome:
87 -> 69 Mb
FireFox (can't measure because it does not show memory usage, just allows to take stapshot):
263 -> 261 Mb
screenshot for Safari@MacOS:
=> parseJson: improve memory footprint using string table in object2JsonStructs native

lib/formats/json/json.flow
`getJsonBoolValue` is working with `JsonString` but `getJsonStringValue` cant get value from `JsonBool`.
Seems like it was never needed.
Added a convertation from bool to string.
Usages of this function seems not to work with bool, but I checked it briefly and only what I could find my projects.
=> getJsonStringValue - bool2string added

platforms/js/DisplayObjectHelper.hx
It reduce time to render from 9 seconds down to 6. profiler data looks better too
with last commit:
=> DisplayObjectHelper: tune critical functions

lib/fform/renderfform.flow, lib/form/form.flow, lib/form/formtransforms.flow, lib/form/renderform.flow, lib/material/iscript/material_iscript_form.flow, lib/rendersupport.flow, platforms/js/FlowSprite.hx, platforms/js/RenderSupport.hx
We need it for https://trello.com/c/enLKYnGG/11767-mobile-device-frames-looks-bad.
Is there a better way to detect pixel data from img?
Or maybe even get rid of the check? https://github.com/area9innovation/flow9/blob/master/platforms/js/TextClip.hx#L1072
=> JS. getClipAt. Check pixel alpha.

lib/material/internal/material_dialog_internal.flow
- close MDialog when `closeWhen` is really changed to true (previously it was closed whenever `closeWhen` was changed to any value)
- do not open MDialog if `closeWhen` is false
=> fixed processing of MDialog's `closeWhen` parameter

platforms/common/cpp/core/ByteCodeRunner.h, platforms/qt/bin/windows/QtByteRunner.exe
It increases chance to run fast garbage collection instead of full garbage collection, so it speeds up QtByteRunner.
Command `update --only-master-key --profile` now takes 25 sec. instead of 3.5 min for rhapsode.
=> Increased ephemeral memory values

lib/fform/fform.flow, lib/fform/fformmetrics.flow, lib/fform/fformutils.flow, lib/fform/optimizefform.flow, lib/fform/renderfform.flow, lib/fform/sfform.flow, lib/material/internal/debug_subscribers.flow, lib/material/internal/material_focus.flow, lib/material/iscript/material_iscript_form.flow, lib/rendersupport.flow, lib/tropic/tropic.flow, lib/tropic/tropic2form.flow, lib/tropic/tropic2string.flow, lib/tropic/tropic_metrics.flow, lib/tropic/tropic_optimize.flow, lib/tropic/tropic_paragraph.flow, lib/tropic/tropic_paragraph_types.flow, lib/tropic/tropic_profile.flow, lib/tropic/tropic_resolve_css.flow, lib/tropic/tscroll.flow, platforms/js/DisplayObjectHelper.hx, platforms/js/FlowContainer.hx, platforms/js/RenderSupport.hx
This fix is intended for cases when content into dialog with scroll has a stroke. At some positions, this stroke happens to be cut. For now, hotfix is to wrap content into 1 px border : https://github.com/area9innovation/innovation/blob/master/components/mwigi/mwigi/mw_dialog_utils.flow#L190, but it would be better to fix it on js level.
Is it appropriate? Should we additionally call invalidateTransform?
=> JS. FlowContainer. Added cropEnabled.

lib/fform/fform.flow, lib/fform/fformutils.flow, lib/fform/sfform.flow, lib/form/paragraph3.flow, lib/formats/html/form2html.flow, lib/stylestructs.flow, lib/sys/target.flow, lib/tropic/tropic2form.flow, lib/tropic/tropic_ui.flow
In Safari, the text behaves like dynamic element regarding its metrics so we can't measure it in advance.
for example, the real metrics of the text is changes in case the scale is changed. but from pixi (canvas) point of view nothing changed.
=> Wigi: make text metrics dynamic for Safari

lib/fform/fform.flow, lib/fform/renderfform.flow, lib/fform/sfform.flow, lib/rendersupport.flow, platforms/js/RenderSupport.hx, platforms/js/TextClip.hx
linked with https://github.com/area9innovation/innovation/pull/2112
in JS when pasting into FTextInput, we receive input both from paste and typing
but in WIGI we process pasting from global paste listener (special event Paste) so it leads to double processing of the pasting text.
this new filter allow to get type of event
=> JS: introduce FInputEventFilter

platforms/js/PixiWorkarounds.hx, platforms/js/RenderSupport.hx
=> Fix PIXI.TextMetrics.measureFont on MacOS

lib/ds/arrayutils.flow
It addresses "Maybe iterASync could be implemented simpler than using foldiAsync2" not to get stack overflow.
=> Make foldiAsync2 tail recursive

lib/form/paragraph3.flow, lib/form/paragraphtypes.flow
Added borders highlight for annotated images:
**Related PR:** https://github.com/area9innovation/innovation/pull/2256
=> Added highlight for annotated images

lib/form/paragraph3.flow, lib/tropic/tropic_paragraph.flow
Currently, the superscript position is based on the height of the character immediately before it.
=> Changed the positioning of the text-superscript

doc/linux.markdown
Fixed link to the `Compile Flow itself (Optional)` section form table of contents.
=> fixed table of contents link in doc/linux.markdown

lib/formats/html/html2form.flow
https://trello.com/c/LRlGziTB/13835-zoom-icon-appears-twice-in-the-basic-image-editor-for-some-cropped-images
=> Fix double zoom button

lib/form/mathdrawing.flow
https://trello.com/c/t6Dp2VKd/13073-wigi-dotted-element-alignment
**Before:**
**After:**
Related PR https://github.com/area9innovation/innovation/pull/2411
=> Remove extra space around WigiDottedElement

tools/flow9/backends/cpp/cpp_backend.flow, tools/flow9/tests/cpp/array_index.flow
fix the error: ‘__index’ was not declared in this scope
=> Flow9 : register __index

tools/flow9/backends/cpp/cpp.flow, tools/flow9/backends/cpp/cpp_backend.flow, tools/flow9/backends/cpp/flow_natives.hpp, tools/flow9/backends/type_hierarchy.flow, tools/flow9/tests/cpp/array_fns.flow, tools/flow9/tests/cpp/fn_arg_type.flow, tools/flow9/tests/cpp/return_void.flow
- ':='
- 'return {};' and 'return (fn(); {});'
- error: template argument deduction/substitution failed (WIP)
=> Flow9 : fixes for c++

tools/flowc/flowc_version.flow, tools/flowc/typechecker/initorder.flow
Fix to the:
When a variable is mutually dependent on a function, i.e. there's no
strict dependence precedence between a variable and function,
if we put typechecking of a function before typechecking of a variable,
typecheker fails. So, in such situations we put all variables before
function in init order.
Appended:
When we resolve init order in a group of mutually dependent names:
a) place all vars before functions
b) order vars by dependency
c) order funcs by dependency
https://trello.com/c/4GmNFWsZ/794-compiling-depends-on-naming
=> Flowc fix initorder

lib/material/internal/filebrowser/material_filebrowser_internal.flow, lib/material/internal/filebrowser/material_filebrowser_internal_view.flow, lib/material/internal/material_grid.flow, lib/material/material.flow
Additionally add preview of the pictures in search mode.
https://trello.com/c/cMevJitP/16244-speed-up-filebrowser-for-large-partitions?filter=label:Release%202.5
=> Previews for pictures that displayed on the screen instead of all.

doc/form.markdown, resources/vscode/flow/README.md
CharacterStyle is indeed a union, not a subtype. And I think full path to flow.vsix is clearer.
=>  small doc improvements for flow and vscode 

lib/form/paragraph3.flow
Try to make Justify and join-text optimization work together
Under flag js_justify it uses WordSpacing css style instead of arranging words manually
=> Wigi: make justify in JS WordSpacing-based

lib/net/http.flow, lib/net/http_types.flow, platforms/common/cpp/core/STLHelpers.h, platforms/common/cpp/core/Utf8.cpp, platforms/common/cpp/utils/AbstractHttpSupport.cpp, platforms/common/cpp/utils/AbstractHttpSupport.h, platforms/js/HttpCustom.hx, platforms/js/HttpSupport.hx, platforms/js/Native.hx, platforms/qt/bin/windows/QtByteRunner.exe, platforms/qt/bin/windows32/QtByteRunner.exe
New parameter for the requests to get data in specific encoding. Or, to get data from the request in the same encoding for the different targets (js, cpp).
Now supports 4 encoding:
* ResponseEncodingAuto() - default, as was;
* ResponseEncodingUtf8(withSurrogatePairs = true) - js style;
* ResponseEncodingUtf8(withSurrogatePairs = false) - cpp style (but for cpp will be cropped by two bytes);
* ResponseEncodingByte() - without encoding, raw bytes (as string).
Compiler or url parameter/flags takes precedence:
* cpp flag is `use_utf8_js_style`;
* js flag is `utf8_no_surragates`.
=> added `responseEncoding` parameter into http request

lib/form/paragraph3.flow
GlueTextFragments style was implemented using ParaOneWord  with defined Cols inside, it leaded to the broken interactive elements.
Replaced with ParaWordGlued - it instructs Word Grouping algorithm to keep words on the same line
=> Replace ParaOneWord with ParaWordGlued

platforms/qt/bin/cgi/linux/QtByteRunner.fcgi, platforms/qt/cgimain.cpp
This will allow serverbc runner to recognize use_utf8_js_style url parameter as special and adjust Utf8 global bool basing on it.
=> Cgi utf8 js style

lib/form/virtual_screen_types.flow
https://trello.com/c/SsGZGu61/19217-wrong-order-of-closing-wigi-popups
Related PR:
https://github.com/area9innovation/innovation/pull/3049
https://git.area9lyceum.com/Lyceum/lyceum/pulls/5432
=> Fix virtual screen overlays closing order

lib/material/internal/material_tabs.flow
fill the icon by the same color as its heading when the "Color Selected Tab Text" is used, so the icon and text are in harmony
=> Fill an icon in a tab the same color as text heading

tools/gringo/type/output_types.flow
grammar example :
```
templates = ("[" ws templateName "]" ws) | $"nil";
templateName = $"nil" $templateid $"cons"("," ws $templateid $"cons")*;
function = optexport id templates ws "(" lambdaargs ")" ws "->" ws type exp decl $"function_7";
```
-> function = _name\[T\](...)->..._ or _name(...)->..._
Empty list is only allowed in GTypeUnion, not as a type or whatever
@alstrup  is PR the right fix?
=> Gringo : optional parameters

platforms/java/com/area9innovation/flow/FlowRuntime.java, platforms/java/com/area9innovation/flow/Struct.java
https://trello.com/c/F2qM0Gz0/19450-for-json-serialization-should-not-use-e-notation-for-integers
cpp: 
source string: "[{\"id\": 100405271}]"                                                                                                                                                                                                                                         parsed json: JsonArray([JsonObject([Pair("id", JsonDouble(100405271.0))])])     
java before fix:
source string: "[{\"id\": 100405271}]"                                                                                                                                                                                                                                         parsed json: JsonArray([JsonObject([Pair("id", …
=> make java 'double' serialization uniform with cpp backend

lib/net/http.flow
`setHttpRequestArgsUpdater` function can be used for:
1. Collecting requests (all, failed or successful);
2. Updating request parameters or headers;
3. Rejecting some requests;
4. Performing some requests on client side;
=> Introduced `setHttpRequestArgsUpdater` function

platforms/common/haxe/HaxeRuntime.hx, tools/flowc/backends/javascript/fi2javascript_compile.flow, tools/flowc/flowc_version.flow
`println` in js target works differently depending on "debug=1" flag, both are weird.
The test case.
```flow
import runtime;
main() {
println("string");
println(Some("string"));
println("Output: " + toString(Some("string")));
println(["a", "\n", "c"]);
println(ref "1\n2");
quit(0);
}
```
Output without "debug=1"
Output with "debug=1"
After the fix the output does not depend on the flag and is the same as in cpp target:
=> Fixed `println` in js target

lib/material/material_fontstyle.flow
[Slideshow] Fixing bug: text styles apply different from Roboto fonts in wigi text
=> [Slideshow] Fixing bug: text styles apply different from Roboto fonts in wigi text

platforms/js/FlowSprite.hx
- https://trello.com/c/Bp8dMc7w/2485-pngs-in-svg-containers-arent-scaled-properly-on-retina-displays
Before
After
=> Fix svg scaling with Chrome

tools/flowc/backends/html/fi2html_utils.flow
https://trello.com/c/4QaGoBQm/19122-rhapsode-is-translated-in-chrome-by-google-translate-even-if-you-the-webpage-is-in-the-language-you-have-prefered-in-browser
=> Missing space in HTML

tools/flowc/manipulation/lambda_lifting.flow
the issue : 
```
fnMy(start : double, fn : (double) -> void) -> void { }
fnMy(2.1, \i -> println(i) );
```
-> lifted lambda has _**i : flow**_, but should be _**i : double**_.
this test is ok (the result is 2 lambdas with the correct types (double, int) : 
```
fnMy2(start : double, fn : (?) -> void) -> void { }
fnMy2(2.1, \i -> { i+1.1; {} });
fnMy2(2.1, \i -> { i+1; {} });
```
@alstrup  is there a better way to fix it ?
=> Lift Lambda : replace Flow type with the declared one if possible

lib/runtime.flow, lib/string.flow, platforms/common/haxe/HaxeRuntime.hx, platforms/java/com/area9innovation/flow/Native.java, platforms/js/Native.hx
See: https://trello.com/c/3INoUjvF/20971-mks-java-creates-invalid-json
The JSON string formatting was broken for all none JS targets. That includes Java and flowCpp. 
I have added a new Native for Java, that should escape correctly. 
All other targets now uses the default Flow implementation.
=> toStringForJson native

lib/ui/fontmapping.flow, tools/flowc/backends/inca/lift_types.flow, tools/flowc/completion.flow, tools/flowc/flowc_find.flow, tools/flowc/incremental/fiprettyprint.flow, tools/flowc/manipulation/deadtypes.flow, tools/flowc/manipulation/flatten_unions.flow
* bug with not all types accounted as used is fixed
* prettyFiDeclaration prints body of functions/vars, not only types
* old prettyFiDeclaration is now prettyFiDeclarationType - prints only type
* unused parameters are removed from prettyprinting functions
=> flowc: flatten unions is fixed

lib/form/paragraph3.flow, lib/form/paragraphtypes.flow, lib/tropic/tropic_paragraph.flow
https://trello.com/c/pceMXgxC/21565-funky-preview-behaviour-for-readers-with-tables-that-have-been-placed-in-brackets
=> Tropic Wigify: text after filler should not be kept on same line

lib/tools/dsl/dsl_parse.flow
The definition of `grammar_extension` as raw string breaks the vscode
syntax highlighting, so extracting it to a separate variable and moving
it to the bottom of the file makes code mode readable
=> Dsl parse made more readable

tools/common/compilerconfig.flow, tools/flowc/backends/common.flow, tools/flowc/flowc_interpreter.flow, tools/flowc/flowc_local.flow, tools/flowc/flowc_repl.flow, tools/flowc/flowc_version.flow, tools/flowc/manipulation/compile_time.flow, tools/flowc/manipulation/deadcode.flow
// Try to find a named constant from config and pass it to AST.
// The definition of constants in options is done with `env` option and looks like:
//    env=bar=1,js=true,bit_width=32,pi=3.14,app_id=A9_APP
//
// If `env` option is defined in flow.config file, more sparse format is available:
//    env += bar = 1
//    env += js=true, bit_width = 32
//    env += pi = 3.14, app_id=A9_APP
//
// Following types of compile-time constants are supported:
//    boolean, integer, double and string
//
// LIMITATIONS:
//  - spaces, tabs, etc. are not allowed in string values
//  - commas are not allowed in string values
//  - booleans are of the form: 1, 0, true, false, TRUE, FALSE
//
=> Flowc compile time env vars

tools/flowc/backends/build.flow, tools/flowc/flowc.flow, tools/flowc/flowc_usage.flow, tools/flowc/flowc_version.flow, tools/flowc/manipulation/compile_time.flow
Particular backends may be excluded from build by overriding variables in flow.config with `env` option, like:
`env += fc_enabled_lisp_backend=0`
or
`env += fc_enabled_lisp_backend = false`
or passing an explicit set of values of variables to the compiler via command line, i.e.:
`flowc1 jar=flowc_compact.jar file=flowc
env=fc_enabled_bytecode_backend=1,fc_enabled_javascript_backend=0,fc_enabled_html_backend=0,fc_enabled_java_backend=1,fc_enabled_rust_backend=0,fc_enabled_nim_backend=1,fc_enabled_d_backend=0,fc_enabled_lisp_backend=0,fc_enabled_cpp_backend=0,fc_enabled_protobuf_backend=0,fc_enabled_speedy_backend=0,fc_enabled_ml_backend=0,fc_enabled_doc_backend=0,fc_enabled_wasm_backend=0,fc_enabled_flow_backend=0,fc_enabled_cpp2_backend=0,fc_enabled_wise_backend=0,fc_enabled_cpp3_backend=0 …
=> Flowc enable choice of backends

tools/flowc/backends/java/fi2java_compile.flow
That fixes example
`import date;
main() {
getCurrentDate().year - 5*2;
}`
=> Flowc: Fix Java field accessor generated code

lib/material/internal/filebrowser/material_filebrowser_internal_types.flow
https://trello.com/c/XEpp2Qho/23161-files-usable-in-slideshow-not-allowed-by-file-picker
=> add jfif extension to file picker

lib/form/videoform.flow
https://trello.com/c/DJM7uy2Q/23391-adding-a-youtube-or-vimeo-player-as-an-embedded-website-in-wigi-should-show-their-policy
=> Show Policy for video links

lib/tropic/tropic_paragraph.flow
https://trello.com/c/8vqgULMZ/942-styles-are-not-applied-to-leading-spaces-in-tropicwigify
=> Fix words grouping for leading spaces

lib/tropic/tropic_paragraph.flow
https://trello.com/c/8vqgULMZ/942-styles-are-not-applied-to-leading-spaces-in-tropicwigify
=> Fix words grouping for space in the end of group.

lib/dynamic.flow, platforms/java/com/area9innovation/flow/Native.java, tools/flowc/flowc_version.flow
No need to have extra native `runtimeValueType`, when we already have `getDataTagForValue` native.
=> Flowc make runtime value type not native

lib/ui/imagedecorated.flow
=> Fixed dimmer in images with custom size less then actual size.

lib/material/internal/material_menu.flow
https://trello.com/c/pagm9qUt/23486-its-impossible-to-operate-with-keyboard-in-match-drag-and-drop-mode
=> remove arrow navigation in menu in the case if there is only one item

tools/flowc/callgraph.flow, tools/flowc/flowc_local.flow, tools/flowc/flowc_usage.flow, tools/flowc/flowc_version.flow
Call paths to global variables are also considered:
`Flow compiler (3rd generation)
Call paths from 'make3DBoxGeometry' to 'prime3DSceneGUIStyle'':
make3DBoxGeometry -> makeM3DEditor -> makePrimeLyceum3DEditor -> showPrime3DSceneEditDialog -> prime3DSceneGUIStyle
make3DBoxGeometry -> renderF3DGeometry -> render3dform -> F3DStage -> T3DStage -> makeM3DEditor -> makePrimeLyceum3DEditor -> showPrime3DSceneEditDialog -> prime3DSceneGUIStyle
done in 53.6s`
=> Flowc callgraph include vars

lib/material/internal/material_tabs.flow, lib/material/material.flow
This PR adds MListReorderStyle to MTabsStyle and fixes tab header width for MWidthByContent() with MTabsAddAction()
By default MListReorderStyle has MReorderOnDragEnd() because it seems like an expected behavior in most cases
Related PRs: https://git.area9lyceum.com/Lyceum/lyceum/pulls/7814
=> MTabsStyle: Add MListReorderStyle

platforms/js/RenderSupport.hx
In some cases modifier keys get stuck when browser loses focus but "blur" event is not fired, in particular when "Mission control" is triggered on mac. This pr adds preventStuckModifierKeys to onpointerdown to check stuck modifiers to fix the issue in this card: https://trello.com/c/HgWoJyV2/410-multiselection-is-often-the-default-on-mac
=> RenderSupport: Add preventStuckModifierKeys to onpointerdown

platforms/js/TextClip.hx
https://trello.com/c/a9rFt9pm/24377-math-font-numbers-jump-around-in-learner
=> JS. TextClip. Alternative fix for Amiri jumps.

lib/material/tests/test_text_metrics_with_scale.flow, platforms/js/TextClip.hx
This PR skips applying transform to `textNodeWidth` in `updateTextWidth` if `useCheck=true`. `getTextNodeMetrics` with `useCheck=true` calls `updateTextNodesWidth` which attaches the svg to the body in `updateTextNodeWidth` ignoring transform applied to the text clip. As result we should skip dividing width by this transform as it was never applied. Not sure if this is a correct and only place to ignore transform.
Added a test `lib/material/tests/test_text_metrics_with_scale.flow`
without fix:
with fix:
=> TextClip: Ignore transform if useCheck is true

lib/material/internal/material_textinput_state.flow, lib/material/material.flow
This PR adds MFullHeight style that allows MTextInput to take full available height and MInactiveOpacity that allows to change opacity for inactive MTextInput elements.
=> MTextInputStyle: Add MFullHeight, MInactiveOpacity

lib/fform/fform.flow, lib/fform/renderfform.flow, lib/fform/sfform.flow, lib/material/internal/material_textinput_state.flow, lib/material/internal/material_theme.flow, lib/material/internal/material_typography.flow, lib/material/material.flow, lib/material/material_color.flow, lib/rendersupport.flow, platforms/js/RenderSupport.hx, platforms/js/RenderSupportNodeJs.hx, platforms/js/TextClip.hx, www/flowjspixi.css
This PR adds BackgroundFill to MTextStyle and implements a workaround for autofill inputs in chrome to enforce background color.
Related PRs: https://trello.com/c/VhbGwsyZ/568-use-dark-background-for-login-text-inputs
=> MTextStyle: Add BackgroundFill

lib/material/tests/escape_html_test.flow, platforms/js/TextClip.hx
This PR disables useCheck for TextClip in case escapeHTML is true. Attached a test to reproduce the problem:
`lib/material/tests/escape_html_test.flow`
Before fix:
After fix:
=> TextClip: Disable useCheck if escapeHTML is true

lib/ds/array.flow
During the test with Bridge's fixup for creator, we see that browser crash if there are 2M of contents ids that should be slitted in group of 1k ids.
The cause is the recursion in splitByNumber, so I modify it to use tail recursion
=> [splitByNumber] Use tail recursion to avoid out of memory error

lib/formats/json/json.flow
return the position of the character that was last extracted.
We return the number of the first character of the object that is not complete and the data after that character. we need the last processed index sometimes
=> Parse Json with errors 

lib/fusion.flow
Do not use `fold` in `fmaxA`, `fminA` because it causes a crash when the array is longer than 10K.
But maybe we still need to use `fold` with short arrays?
hotfix for lyceum is here https://git.area9lyceum.com/Lyceum/lyceum/commit/ee1ccced0d7b33cb0d2740b75e42adbe143135f2
trello https://trello.com/c/dWCgbsTq/25448-attempting-to-load-a-big-class-over-10k-learners-crashes
=> Do not use `fold` in `fmaxA`, `fminA`

lib/formats/html/html2form.flow, lib/ui/imagedecorated.flow
Task https://trello.com/c/gCvynpWQ/25311-when-zoom-is-enabled-allow-zoom-when-clicking-on-image-not-only-clicking-on-the-small-icon
=> Allow to disable the 'zoom by click on image' feature

lib/material/internal/material_player.flow
Task https://trello.com/c/ObgeYAnO/25564-video-subtitles-have-too-large-black-background-boxes
=> Subtitles: draw text without extra background

lib/tropic/tropic_paragraph.flow
https://trello.com/c/S8FpPc9E/25394-prime-graphics-right-alignmented-text-are-not-presented-in-line-after-an-automatically-line-break
=> RtrimWords in lines for Right alignment

lib/material/material_ui.flow
Task https://trello.com/c/nBXxF9wN/25622-coach-sometimes-plays-twice-on-top-of-one-another-using-safari
Sometimes Safari on MacOS and iPad launches all fragments at once and they can not be paused by isPlay[i] (because it is false at that moment).
So for Safari I suggest starting all the fragments quietly, pausing them, and then returning the volume to the initial value and starting the whole playlist from the beginning if necessary (if autoplay is on)
@NikitaFil @stanislavpodolia any objections?
=> MMultiAudioPlayer: start all fragments muted in Safari

lib/formats/uri3/uri3.flow
https://trello.com/c/DGomPo92/26091-command-shift-k-adding-spaces-in-url
=> Always encode spaces in the url

platforms/java/com/area9innovation/flow/Native.java
The funcion class name pattern looks like:
`tools.flowc.flowc.Module_eval$$Lambda/0x000071317c1ab2e0` thus we need to check for "$$Lambda", not for "$$Lambda$
=> flowc: `getDataTagForValue` for functions returns correct value

lib/material/internal/material_button.flow
https://trello.com/c/WyJa6hVy/26738-the-checkboxes-in-challenge-us-must-have-a-meaningful-label
=> Added a meaningful label to the Challenge Us checkboxes

lib/sys/keyboard.flow
https://trello.com/c/iUVQrWGX/27123-keyboard-focus-doesnt-move-out-of-the-text-editor-in-math-and-projects
=> Introduce isAltIn

lib/formats/html/html.flow
The `&sol` means [direct
slash](https://www.toptal.com/designers/htmlarrows/punctuation/slash/).
=> The `&sol` html escape is added

lib/formats/html/html2md.flow
The `<code> CODE </code>` is translated to `CODE` or ```CODE```
=> The support for the `code` tag is added

tools/flowc/backends/cpp3/fi2cpp3_build.flow, tools/flowc/backends/cpp3/fi2cpp3_source.flow, tools/flowc/backends/cpp3/fi2cpp3_structs.flow, tools/flowc/backends/cpp3/natives/dynamic.nats, tools/flowc/backends/cpp3/natives/runtime.nats, tools/flowc/backends/cpp3/natives/string.nats, tools/flowc/backends/cpp3/natives/sys_concurrent.nats, tools/flowc/backends/cpp3/natives/sys_system.nats, tools/flowc/backends/cpp3/natives/timer.nats, tools/flowc/backends/cpp3/runtime/__flow_runtime_struct.hpp, tools/flowc/backends/cpp3/runtime/__flow_runtime_threads.cpp, tools/flowc/backends/cpp3/runtime/__flow_runtime_threads.hpp, tools/flowc/backends/cpp3/runtime/__flow_runtime_types.hpp, tools/flowc/backends/cpp3/runtime/timer.runts, tools/flowc/statements/fs_helpers.flow, tools/flowc/statements/fs_perceus.flow, tools/flowc/statements/fs_transform.flow
The `cpp3` backend is updated and made in-sync with the current state of the standard library. Some bugs are fixed.
Now `flowc` may bootstrap itself on the `cpp3` backend, e.g. by executing following command in the `tools/flowc` directory:
```
flowc1 \
cpp3=flowc2 \
cpp-build-jobs=<choose appropriate number of workers> \
cpp-verbose=1 \
server=0 \
cpp-compiler=clang++ \
cpp-mimalloc=1 \
dce-types=1 \
\
flowc
```
This build command assumes, that `clang++` and `mimalloc` are installed on the system. That's the most fast option, in case you use default c++ compiler and no mimalloc library, just remove appropriate lines from the command.
**NOTE:** The number of workers typically depends on the amount of RAM available: with 16Gb of RAM it's better to set it not more then 4. With 64Gb of RAM …
=> Flowc cpp3 backend fixes

lib/ds/tree.flow, tests/valuest2array_tree_speed.flow
New implementation is slightly slower if values of the resulting tree are shorter then about 300 elements,
but it is much faster if this tree has values with more than a thousand elements.
Speed test
```
Compare values2arrayTree speed on array of 100000 elements, splitting this array into ~100000 parts by ~1 elements
*New function: 292 ms
Old function: 301 ms
Trees are exactly the same. Tree size: 63355
Compare values2arrayTree speed on array of 100000 elements, splitting this array into ~100000 parts by ~1 elements
*New function: 262 ms
Old function: 303 ms
Trees are exactly the same. Tree size: 63237
----------
Compare values2arrayTree speed on array of 100000 elements, splitting this array into ~50000 parts by ~2 elements
New function: 281 ms
*Old function: 264 ms
Trees are exactly the …
```
=> Rework `values2arrayTree` using List;

lib/form/gui.flow
https://trello.com/c/MJJRQglI/27867-wrong-behaviour-of-a-text-cursor-in-fixed-size-tables-with-interactive-elements
=> Add outScaleFactor to shrinkToFitB2

platforms/js/PixiWorkarounds.hx, platforms/js/TextClip.hx
- under "use_native_measurement=1"
https://trello.com/c/JzDzVWJW/28115-pgs-can-look-different-on-different-computers
=> JS. TextClip. Added native font properties measurement.

lib/form/formmetrics.flow, lib/tropic/tropic_paragraph.flow
https://trello.com/c/ZnfhB18J/28270-incorrect-words-width
=> Wigi Text. Respect RTL when inspect static Tropic metrics.

lib/material/internal/material_textinput_state.flow
https://trello.com/c/Zd72xlPi/28641-missing-accessible-name-of-input-in-bummer-dialog
=> remove "aria-label" if we have "aria-labelledby"
